### ISSUE TITLE
How to handle "variants" of a schema.

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#10]
***Hypothetical scenario***:

User `DOUG` creates a new schema named `D_SCHEMA`, which consists of two characters - `SIZE` and `COLOR`. Character `COLOR` has three possible states - `RED`, `GREEN`, or `BLUE`.

User `ANDREW` likes `D_SCHEMA`, but he wants to use a slightly different version.
*Andrew's Changes*:
1. **ADD** new state `PURPLE` to character `COLOR`
2. **REPLACE** state `GREEN` with new state `YELLOW`
3. **SYNONYMIZE** state `RED` with new state `CRIMSON`

What is the best way to represent this in the database?

**Comment by aazaff** [comment]
There are two end-member solutions, with a gradient between them.

*Type 1-Extreme*:
Create an entirely new schema `A_SCHEMA` that is a full duplicate of `D_SCHEMA` with the various changes added, and then add some sort of `:IS_VARIANT_OF` tag from `A_SCHEMA` node to the original `D_SCHEMA` node.

*Type 2- Extreme*:
Add new nodes to the existing `D_SCHEMA` tree, but flag them in the properties as being variants.

**Comment by aazaff** [comment]
After my meeting with the NEO4J people, I actually think that Type-2 is closer to the graph way of thinking.

**Comment by NoisyFlowers** [comment]
I'm wondering if Type 1 would behave better when we run the comparison function on a new specimen. But I suppose, in the case of Type 2, we could build whether or not to use variant nodes into the compare function.

**Comment by aazaff** [comment]
This is essentially solved by the recent rework to `:Description` nodes described in #12 - i.e., we just handle it in an analogous to way to the OTU and Specimen relationship

`:Schema {type: "original"}`
`:Schema {type: "variant"}`
