### ISSUE TITLE
Possible bug in edited  book of contributed articles

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#102]
When Ellen hit submit and had a complete entry, nothing happened. When Ellen hit submit without having entered all the required fields, she did get the correct screen telling me what required fields were missing.

**Comment by NoisyFlowers** [comment]
This was the result of author validation when authors are not required on this publication type. I've changed the way authors are handled across the various types. This is in commits:

> paleobot/pbot-client@9dd5eaf306dbf9383749a50ada51997ba5226dd8
> paleobot/pbot-client@b759161f1ff0e6ba81abe8793af9162430c9525c
> paleobot/pbot-client@6a8129403e9c66a157a778ae08c2ddc7c0cf570d
