### ISSUE TITLE
Corrections for the Collection Node, Age fields

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#104]
1. instead of “Date Type” rename “Units”
2. Decimal points are not saved in the various Age fields.

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@fc6e04c165e7878c659d1792321f14f4c8abe943
paleobot/pbot-client@9549fd7783064155946356b0e238eb5b975861e6
paleobot/pbot-client@a7901df93ef8ea2a610d466e6f26fae0234217cc
