### ISSUE TITLE
Automatic "UserName Personal Workbench" group on registration

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#105]
It would be a nice feature to have a "UserName personal workbench" group automatically created upon registration.

**Comment by aazaff** [comment]
I really love this idea.

**Comment by ecurrano** [comment]
I've noticed that rather than having one private workbench, I like to make different ones for each projects to 1) keep myself a bit more organized, and 2) be able to share different data with each collaborator. Of course, the downside to this is that I need to remember to search all of my groups when doing any search...

I'm ok with closing this issue and prioritizing other tasks.

**Comment by doricon** [comment]
I think we should add instructions about this to a general use document, and/or to the group node instructions.
