### ISSUE TITLE
Add person error

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#107]
Add Person: Tried to add a person, entered all required and optional fields. Received error message “Missing required relationship groups”.

Ellen also had mixed abilities to edit person nodes. Sometime it worked fine and sometimes she got “Missing required relationship groups” error message.

**Comment by NoisyFlowers** [comment]
I am making the MEMBER_OF relationship optional for Person nodes. This is in commit:
paleobot/pbot-api@66a3b34676dbadbf6fb20254b9c416754b44bba0
