### ISSUE TITLE
Unsupported image types--investigate and make decision about how to proceed prior to HackAThon

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#109]
As of 230629 10:15am EDT, .svg and .tiff files were not supported. Doug tried to get .svg working yesterday, but when I entered a .svg image I received this message: Error: Cannot read properties of undefined (reading '_fields'). 

Andrew to investigate to see what can be done, if we want to make any changes, and if we need to restrict image types for HackAThon only or generally going forward.

**Comment by clairecleveland** [comment]
We also would like to provide a message to user using hover or a notation on the form that defines which types and size of files are permitted.

**Comment by NoisyFlowers** [comment]
svg and tiff should be working now
