### ISSUE TITLE
Image size rules--investigate for HackAThon

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#110]
Do we want to restrict image sizes and if so, what is the size limit? Andrew to investigate with Doug and let us know of any restrictions so researchers can prep for HackAThon.

**Comment by clairecleveland** [comment]
Note: Image max size was set to 10 MB for the Hackathon.

**Comment by NoisyFlowers** [comment]
Image size limit on dev is currently set to 15MB. 

Should I set to 10MB?

**Comment by aazaff** [comment]
15 is good

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: NoisyFlowers ***@***.***>
Sent: Friday, July 21, 2023 12:50:06 PM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Assign ***@***.***>
Subject: [EXT]Re: [paleobot/pbot-dev] Image size rules--investigate for HackAThon (Issue #110)


External Email

Image size limit on dev is currently set to 15MB.

Should I set to 10MB?
