### ISSUE TITLE
General Issue: Special characters not allowed--try for HackAThon, but not promised

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#113]
We would like to allow special characters as many of our international users would like to use them and things like "" are important in comments. Currently we get this error:  “Error: Invalid input 'H': expected whitespace, '.', node labels or rel types, '[', '^', '*', '/', '%', '+', '-', "=~", IN, STARTS, ENDS, CONTAINS, IS, '=', "<>", "!=", '<', '>', "<=", ">=", AND, XOR, OR, ',' or ']' (line 57, column 74 (offset: 2289)) " baseNode.caption <> "Fruits and Seeds Character "Hull" State "hairy" illustrated by Michael Rothman. Filename: PBot_FruitsAndSeeds_MichaelRothman_HairyChar_Rambutan_230208.jpg"," ^.

In addition, we need to consider if we want to allow italicized text and how that could be implemented. Not currently available. [ITALICS ISSUE IS NOT REQUESTED FOR HACKATHON]

**Comment by NoisyFlowers** [comment]
It would help to see the actual text string you are trying to input. Can you paste that here?

**Comment by NoisyFlowers** [comment]
I just verified that the special characters listed are already accepted by PBot. Take a look at "repository" and "notes" in 

> [http://128.196.196.17/query/specimen/e341cfee-29d2-490b-bc06-8cf56adefed5](http://128.196.196.17/query/specimen/e341cfee-29d2-490b-bc06-8cf56adefed5)

(note for posterity: that specimen will soon be deleted)

Regarding things that require markup (italics, etc): Markup can be added to text right now (see "notes" in above link). We just interpret it as raw text when output. To interpret it as html, we would need to sanitize it in the browser first. This is possible but not trivial. I'd need to know what fields we want this functionality on. For anything fancier on data entry, we'd need to incorporate a rich text editor for appropriate fields. This too is possible. 

Suggest closing this issue as Complete for the special characters and opening a low priority feature request for the markup.
