### ISSUE TITLE
ORCID ID format enforcement

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#115]
Enforce appropriate hyphens, number of characters, etc. for entering ORCID ID.

**Comment by aazaff** [comment]
Subset of #117

**Comment by NoisyFlowers** [comment]
This is in 

> paleobot/pbot-client@2ea84a98ac38f87d782cb70ea259c56b81fbff3f
> paleobot/pbot-client@0eb702eba9fe75edd546d6e5504ddca71642e467
