### ISSUE TITLE
Delete Person Alert

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#116]
Grey out or remove (-) button/delete button from the Person page for all users who do not have this ability so they don't waste time trying to make it happen. Another option would be to at least give them a message, "You do not have authorization to delete person nodes." or something like it.

**Comment by aazaff** [comment]
I prefer the message approach. Having it greyed out might make them think that the feature is just broken or not implemented yet.

**Comment by clairecleveland** [comment]
@aazaff Sounds good.

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@8708f45aa48a22acf1f7b669370a505db1c86ec4
