### ISSUE TITLE
Add ORCID ID field to Registration page

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#117]

**Comment by aazaff** [comment]
There should also be some validation to make sure it is using valid orcid structure, but that can be separated out into a separate issue/setp.

**Comment by aazaff** [comment]
Yup, looks like validation was already submitted as a separate issue. Now linked.

**Comment by NoisyFlowers** [comment]
This is in

> paleobot/pbot-api@b41b403f36846dbcc2a023f9ef50f2cdbe45fafa
> paleobot/pbot-api@128a87e8f9a9f920ed99d3444d1d31006e07fc33
> paleobot/pbot-client@ef73fdff1fd9e5aad5b8ba555f2ed0f8780768fc
