### ISSUE TITLE
Public vs. private groups

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#118]
Right now Public is listed as an option inside the Group Selection drop down box when adding/editing a group. Should we just remove Public from drop down list. Is is true that once a group goes public the group is no longer valid? Is there a reason researchers would want to keep a group/project live on their workbench once that information has gone public? 

Doug to investigate and provide current status to Botany group.

**Comment by doricon** [comment]
I just wrote a note in the existing issue for groups/public: https://github.com/paleobot/pbot-dev/issues/94#issuecomment-1614892875
Basically, having 'public' in the dropdown list for groups is critical for being able to search for data in either private groups AND the public data. I had to do this yesterday to find an OTU I made!

**Comment by aazaff** [comment]
Let's go over this again with screen-share during our Wednesday 7/5 meeting. I think there maybe be 2 or more fixes that need to be clarified related to this.

**Comment by ecurrano** [comment]
I will be gone this Wednesday, but leave things in Dori's and Claire's capable hands.

**Comment by doricon** [comment]
As a clarification to Andrew's clarification - remove "public" from the Groups selection dropdown list in all forms in the Workbench, but leave it as a multiselect option in the Explore search forms dropdowns. :)

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@da87b0dedde5090a7f1200e76d0b77b511f482c1
