### ISSUE TITLE
Allow delete reference when editing Schema

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#120]

**Comment by NoisyFlowers** [comment]
The problem observed was that a Schema with two or more References did not display the "X" button for delete those beyond the first. 

This is an artifact of old data in the database.

We decided that each Schema can have only one Reference. This was implemented in the recent form update push. Any Schemas in the db that have more than one Reference will behave badly in the new form. 

As this is a case that will not arise going forward, once the db is cleaned up, I'm closing this issue.
