### ISSUE TITLE
Description page: Add notes field inside Optional accordion 

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#121]

**Comment by NoisyFlowers** [comment]
Remove bug designation, as this field is not specified in the fields doc for Description ([https://github.com/paleobot/pbot-dev/blob/main/Field%20definitions/Description%20fields%20v2.md](https://github.com/paleobot/pbot-dev/blob/main/Field%20definitions/Description%20fields%20v2.md)).

**Comment by aazaff** [comment]
It was a bug in the original fields document :)

**Comment by aazaff** [comment]
This raises an interesting problem where we would have to come up with an aggregate method for handling notes from multiple descriptions when we look at a merged OTU. I don't think this will be resolvable before the hackathon so I am removing that tag, but keeping it as high priority.

**Comment by clairecleveland** [comment]
@aazaff I don't think this field should be included in the merged descriptions on OTU. It is not a state and only relevant to specific specimens. If anyone needs to see where a specimen was measured they can get into the nitty gritty by going to that specimens description OR should that be included in a note on the specimen itself instead?

**Comment by aazaff** [comment]
In that case, I think that makes this easier. What do you think Doug?

**Comment by NoisyFlowers** [comment]
Yes.

This is in:

> paleobot/pbot-api@74d68562512d9db6064846cb4fcb5709215fe90f
> paleobot/pbot-client@4a9c02d1b9a0d71735cbb0cfadd5c21a46f39f07
> paleobot/pbot-client@3678b82aa9ac7adaf2bf9d171b92835a69f2bbc3
> paleobot/pbot-client@3b5042305c7d31e586643e39bfd18d31b778a8f2
>
