### ISSUE TITLE
Specimen option tabs shuffle around

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#124]
Move "Other" to be the one that is on the left, and the "iDigBio" one on the right. 

Under the Other tab, put field in this order: 
Notable features preserved
Reference
Identified by
Other repository link
Notes

Hide the GBIF field - i looked into it and also can't figure out a meaningful link to specimen, although you can click through gbif to get to the original record at the primary repository. That link would be accommodated by the "other repository link" field, so we don't need the GBIF one for now.

**Comment by aazaff** [comment]
Strong agree. Just drop the big field. We've discussed this before.

**Comment by NoisyFlowers** [comment]
This is in 

> paleobot/pbot-client@bda8d60fc0e934b64d9c49ae03d9f34477add0f0
