### ISSUE TITLE
Major taxon group list

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#125]
Oops we forgot to give you the list for the drop down for Major taxon group. Our bad. Matt will provide the list early next week and I will update it here!

**Comment by doricon** [comment]
Here is the drop-down list for major taxon:

Sporing non-vascular

Sporing vascular – ferns

Sporing vascular – horsetails

Sporing vascular – lycopsids

Sporing vascular – other

Gymnosperm – conifers

Gymnosperm – ginkgos

Gymnosperm – cycads

Gymnosperm – seed ferns

Gymnosperm – other

Angiosperm – monocot

Angiosperm – ‘dicot’

Undetermined

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@0e74abe15bc376cf0328b966c8bf1b3727bfbee5
