### ISSUE TITLE
"groups" field going grey in Explore 

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#128]
When doing searches in Explore (happening in multiple forms), if I search something, but then switch back from those results to the action tab to redo or refine my search, the Groups selection field is grey-ed out and a selection cannot be changed. I have to refresh page or go to a different form and come back to be able to use it again. I haven't seen that with other fields.

**Comment by NoisyFlowers** [comment]
This is in commit:
paleobot/pbot-client@97548a471c4dd1c74e9343997cc4627b40515a12
