### ISSUE TITLE
Search results for OTU - build out a bit

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#129]
The return info on the search form for OTUs needs to be updates to reflect the newer fields  - this will important for the hackathon, if we can swing it, since folks will be entering OTUs! 

Some things that would be awesome to display there:
-Image(s) from specimens would be fantastic. 
-Direct link to the type specimens (exemplar for sure)
-some geographic info pulled from the associated collections of the specimens

**Comment by NoisyFlowers** [comment]
I've added authority, diagnosis, qualityIndex, majorTaxonGroup, pbdbParentTaxon, and additionalClades to the output. Also a direct link for the holotype specimen, but only when the "include holotype description" box is checked. This is in:

> paleobot/pbot-client@506b1657252b94cf0a9e12bed3ddbaea2f525efd
> paleobot/pbot-client@f1d288d2f705a167b7d4490cc17695af36715364
> 

The rest will take more time. I suggest we deprioritize the other parts of this issue (i.e. post-Hackathon).

**Comment by ecurrano** [comment]
I am closing this as we know that the search and return forms need a lot of updating, and there is nothing particularly useful in this conversation.
