### ISSUE TITLE
Titles for forms

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#130]
Can the forms have titles at the top? I get lost on what is happening without that. I know the sidebar indicates which form it is via the green dot, but having it written at the top above where you are entering seems to be what my brain needs. (like right above required fields or next to the add/edit/delete symbol)

**Comment by aazaff** [comment]
I would like to see what the rest of the team feels about this as it is largely an aesthetic choice.

**Comment by ecurrano** [comment]
I am ambivalent. I didn't get lost in forms, but also didn't put in the massive session that Dori did where I entered lots of different things. This might be a good specific question to ask at the Hack-a-Thon and then move forward accordingly.

**Comment by doricon** [comment]
Sounds good - it could just be a matter of getting used to it/training oneself. (I'm doing better with it now). Let's put on discussion/feedback list for the hackathon. I'll make a working doc for that now.

**Comment by ecurrano** [comment]
No one brought this up at Hack-a-Thon, and I think we have more important issues to finish us out. I'm closing this one.
