### ISSUE TITLE
Reference order, prepopulate first entry to 1

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#132]
Can the reference order be pre-filled to "1" for the first entry? Like with the states.

**Comment by NoisyFlowers** [comment]
This is implemented for References and Authors in paleobot/pbot-client@938f3bf3dbafd16d575f263d3f4cff0d744496fb

**Comment by NoisyFlowers** [comment]
It seems I broke Specimen mutations with the the change to Authors. Investigating...

**Comment by NoisyFlowers** [comment]
Fixed in paleobot/pbot-client@d662d9a04598262703e9532066f3c59839530407
