### ISSUE TITLE
GPS coordinate uncertainty - add units to text

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#133]
For GPS coordinate uncertainty: display this in the field "GPS coordinate uncertainty (meters)"

I had to look up what we were entering here - most fields are self-explanatory, so this would be helpful :)

**Comment by aazaff** [comment]
I consider this related to #135

**Comment by NoisyFlowers** [comment]
This is in paelobot/pbot-client@e34c6b0fbc17b7358259ff3f3b203e17e974b0b2
