### ISSUE TITLE
Settle on aesthetics for supplementary text messages and help

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#135]
We've talked about hover-text etc. as ways to show our help tips. We will need to settle on a specific and consistent *style* for showing additional text information.

The general options for this are the six options below and combinations thereof. We should have a semistandard policy/philosophy for this.

1. in-line help text
2. outside label text
3. popup
4. hover
5. on-click info button
6. placeholder text

**Comment by ecurrano** [comment]
What is the difference between popup and on-click info button? Our preference is for one of these, but we want to make sure we understand the difference.

**Comment by aazaff** [comment]
Do you want it to open a new window? This is good for really long tooltips and instructions, but may conflict with people's popup blockers

Or

Do you want there to be a button that activated a kind of accordion action so that the instructions are shown/hidden within the form itself

Or

Do you want the instructions to simply be permanently displayed at all times?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: Ellen Currano ***@***.***>
Sent: Friday, October 6, 2023 11:14:36 AM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Assign ***@***.***>
Subject: [EXT]Re: [paleobot/pbot-dev] Settle on aesthetics for supplementary text messages and help (Issue #135)


External Email

What is the difference between popup and on-click info button? Our preference is for one of these, but we want to make sure we understand the difference.

**Comment by ecurrano** [comment]
At the top of each page, we'd like a link to the full help-sheet for that form. The hope is that this would open the instructional sheet in a new tab.

Then, there is a need for quick reminders for some entry fields. We like the idea of hover (like what we already have for the PBDB search button), but will this work for our design given that the field names are within the entry field?

**Comment by aazaff** [comment]
I see no problem with the former, but I don’t know what the implications are for the latter. Will have to redirect question to Doug.

From: Ellen Currano ***@***.***>
Date: Friday, October 6, 2023 at 11:43 AM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>, Assign ***@***.***>
Subject: [EXT]Re: [paleobot/pbot-dev] Settle on aesthetics for supplementary text messages and help (Issue #135)

External Email

At the top of each page, we'd like a link to the full help-sheet for that form. The hope is that this would open the instructional sheet in a new tab.

Then, there is a need for quick reminders for some entry fields. We like the idea of hover (like what we already have for the PBDB search button), but will this work for our design given that the field names are within the entry field?

**Comment by ecurrano** [comment]
Sounds good. If it makes a difference, we would plan to use hovers judiciously. Not every field would have one. Just the critically important information (like enter your GPS coordinates in decimal degrees, WGS84!).

**Comment by aazaff** [comment]
We've completely moved away from this idea to having the https://pbot.paleobiodb.org/howto section. If we want to revisit this again in V 2.0, we will open a new ticket, especially since this would have to incorporate PBDB materials anyway.
