### ISSUE TITLE
Re-order elements in workbench toolbar

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#139]
We would like to have the toolbar in workbench reordered to the following. These groupings and order are happier order for us. Preferably by the hackathon :) 

Taxa (OTU)
Description
Collection
Specimen
Image
—
Person
Reference
Group
—
Schema 
Character
State
—
Synonym
Comment

[and please use "Taxa (OTU)" for the display word in the toolbar for both workbench and explore -everywhere else we want to leave as OTU]

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@36e6a2ad352558d4b3d4a99435642503429763d8
