### ISSUE TITLE
Add image filename field to Image node

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#141]
Botany team to determine if we want to specify a place to include image filenames. If so, should it be a separate field or should we train folks on where to include this information.

**Comment by ecurrano** [comment]
I see no need to include the file name. This seems like a perfect place for typos and errors, as image names are commonly specimen numbers which are not the easiest to get right. Also, we need to encourage links, not image uploads, and so people may not even know the image name. Also, reduce what people need to enter.

**Comment by ecurrano** [comment]
Closing since no one argued for having this, and there is a lot else to get done.
