### ISSUE TITLE
Collection type dropdown menu

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#145]
In the collections node, under the collection type dropdown menu, we should have the following options to perfectly match PBDB:
-archeological
-biostratigraphic
-paleoecologic
-taphonomic
-taxonomic
-general faunal/floral

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@c61db4bfb8ce6cca36d1cb1886813d7c4724f6e8.
