### ISSUE TITLE
Preservation modes

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#147]
Our preservation modes do not exactly match the PBDB choices for their collection entry. How shall we handle this? Do I remember correctly that this is a node?

PBot has: charcoalification, compression, impression, mold/cast, other, permineralization, unaltered remains, unknown

PBDB has: body, trace, permineralized, cast, mold/impression, adpression/compression, soft parts, recrystallized, concretion, dissolution traces, charcoalification, coalified.

I think it is fine to have a subset of the PBDB values, as things like "soft parts" don't really make sense for plants. the main problems I see: 
- we have choices PBDB does not, and this is a required PBDB field. 
- we lumped molds & casts, whereas PBDB has cast as an option and lumped mold & impression.

**Comment by aazaff** [comment]
Yes, you should pick an exact subset of pbdb choices

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Ellen Currano ***@***.***>
Sent: Wednesday, July 12, 2023 2:15:18 PM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>; Assign ***@***.***>
Subject: [EXT][paleobot/pbot-dev] Preservation modes (Issue #147)


External Email

Our preservation modes do not exactly match the PBDB choices for their collection entry. How shall we handle this? Do I remember correctly that this is a node?

PBot has: charcoalification, compression, impression, mold/cast, other, permineralization, unaltered remains, unknown

PBDB has: body, trace, permineralized, cast, mold/impression, adpression/compression, soft parts, recrystallized, concretion, dissolution traces, charcoalification, coalified.

I think it is fine to have a subset of the PBDB values, as things like "soft parts" don't really make sense for plants. the main problems I see:

  *   we have choices PBDB does not, and this is a required PBDB field.
  *   we lumped molds & casts, whereas PBDB has cast as an option and lumped mold & impression.

**Comment by aazaff** [comment]
To clarify.

What Dori said makes sense to me. Use whatever the PBOT team wants for specimens, but make the options for collections consistent with PBDB as she described.

RE: the question about why it exists for both collections and specimens – the short answer is simply for legacy compatibility reasons.

From: doricon ***@***.***>
Date: Thursday, July 13, 2023 at 9:35 AM
To: paleobot/pbot-dev ***@***.***>
Cc: Zaffos, Andrew - (azaffos) ***@***.***>, Assign ***@***.***>
Subject: [EXT]Re: [paleobot/pbot-dev] Preservation modes (Issue #147)

External Email

I would like to keep our current PBot options for the specimen node's Preservation field. This is just internal PBot info and doesn't pipe over to PBDB.

For the PBDB field list on collections: I think the following subset should suffice: trace, permineralized, cast, mold/impression, adpression/compression, recrystallized, concretion, charcoalification, coalified

(i don't know how soft parts, body, or dissolution traces would relate to plants - so those are the ones I would nix)

I totally understand if other folks don't want two different lists on different nodes, in which case we will have to standardise to the PBDB version. I don't like their groupings, but also don't have strong sentiment either way! :)

**Comment by aazaff** [comment]
Can we consider asking Mark if they would be willing to add our new/additional types to PBDB as options?

**Comment by aazaff** [comment]
Either way this is too complex to be handled before hackathon.

**Comment by ecurrano** [comment]
For the Hack-a-Thon we do need to match the collection node preservation modes to PBDB's. Here is the subset of PBDB entries that we would like to include:
Body
Trace
Permineralized
Cast
Mold/impression
Adpression/compression
Recrystallized
Concretion
Charcoalification
Coalified

@doricon : I left Body since otherwise I wasn't necessarily sure where to put pollen. You can select multiple, so really someone could select body and many of the choices below. Botany team needs to come up with definitions of charcoalification vs. coalified for the cheat sheet.

**Comment by aazaff** [comment]
We have agreed to go with this final list for both specimen and collection.

**Comment by NoisyFlowers** [comment]
This is in 2062b7f33d73f9104699c60445aab62849f783dd
