### ISSUE TITLE
OTU add two fields

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#150]
Need to add the following two field to OTU form: 

(1) **Parts preserved** (with the standard multiselect drop down list). Put after Authority in the required list.
-The reason we don't pull this from specimens is that the OTU description/diagnosis may be based also on other specimens and parts that are not in our database. This may be particularly common for prior published OTUs. 

(2) **Notes**. Free text field at the end of the optional tab. 

Need by hackathon pleeeease! :)

**Comment by doricon** [comment]
Just following up on whether these fields are getting added to OTU for the hack-a-thon. I am working on the instruction sheets which discuss what to enter for these fields (of these two, I'd say Notes is a higher priority because we can't easily figure out what the entry should be later)

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@1a16e35e45fa6fd270917a47ab2db44304b3cc4a
paleobot/pbot-client@882b15504f7bd882a4bdf40567a6d00b0a7cdffb

As part of this, I also changed the Specimen/OTU to Organ relationship from IS_TYPE to HAS_PART.

I also added notableFeatures to OTU. 

What's weird is both partsPreserved and notableFeatures were once part of OTU. I removed them back in May (paleobot/pbot-client@45234c37816a47be35867ee8d4418ba52b22c2ee). Not sure why.

**Comment by doricon** [comment]
Awesome! Thanks bunches!



Dori L. Contreras, Ph.D.

Curator of Paleobotany
Perot Museum of Nature and Science

E  ***@***.******@***.***>

P  214.756.5783



[pastedGraphic_1.png]<http://www.perotmuseum.org/>



2201 N. Field Street, Dallas, TX 75201  |  perotmuseum.org

[pastedGraphic_2.png]<https://www.facebook.com/PerotMuseum/>

[pastedGraphic_3.png]<https://twitter.com/PerotMuseum>

[pastedGraphic_4.png]<https://www.instagram.com/perotmuseum/>





________________________________
