### ISSUE TITLE
Delete Nodes Collection

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#152]
Database clean up for Hack-A-Thon. Please follow steps below so that Doug can "cleanse" the database prior to the Hack-A-Thon. Perhaps a week before?

Anything nodes that will be used as an example for testing PBot or the PBot Hack-A-Thon, etc. should include the word "test" in the name. 

Please indicate all nodes that are no longer in use and should be deleted from PBot with the word "DELETE" in the name. This way Doug can easily search for all nodes to be deleted.

Additional nodes that should be deleted, but can not be edited:
- Person Node: Claire Cleveland--DUPLICATE

**Comment by aazaff** [comment]
URGENT to discuss for Tuesday 7/25 meeting.

For maximum safety we would like to **save** ALL nodes (and associated relations) of the following types:
1. SCHEMA
2. CHARACTER
3. STATE
4. PERSON
5. REFERENCE

We would like to **delete** ALL of the following nodes prior to the meeting.
1. SPECIMEN
2. COLLECTION
3. IMAGE
4. COMMENT
5. SYNONYM
6. DESCRIPTION
7. OTU

Once these deletes have happened. The pbot team can re-enter relevant examples.

**Comment by NoisyFlowers** [comment]
This is done.

Precleanup db dump is in 
/var/lib/neo4j/import/pbot-1690919730694-preCleanup.cypher

Postcleanup db dump is in 
/var/lib/neo4j/import/pbot-1690922067127-Clean.cypher
