### ISSUE TITLE
Make timescale selection for collections 2-step process

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#158]
1. provide an initial timescale selection -> https://macrostrat.org/api/defs/timescales?all
2. Make available intervals dependent on chosen timescale -> https://macrostrat.org/api/defs/intervals?timescale=
3. Add the numeric age (in Ma) to the interval text in the dropdown

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@936083f8ae48df3de81b31596d857ccfac4065a3
paleobot/pbot-client@07b6b4077afc80b74a4b03b92d1b4c4f231d496c
