### ISSUE TITLE
Replace "Comments on" with "Notes on"

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#161]
We decided to restrict use of the word Comment on PBot to the Comment node. PBDB has various text entry fields that are called: "Comments on ..." For our purposes, is it ok to have a slightly different field name from PBDB? If so, then: 

In the Collections entry form, please update to:
"Notes on geographic information"
"Notes on age information"
"Notes on stratigraphy"
"Notes on environment"
"Notes on collection methods"

**Comment by aazaff** [comment]
Can it just be one word 'notes'?

**Comment by ecurrano** [comment]
My opinion is no, since there are multiple notes fields within the collection (because these each map separately into PBDB) and we want to make it clear what exactly people should write notes about.

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@97915ff4ab16db11ef92d8e0294a006297ac9ea1
