### ISSUE TITLE
Botany team only: policy on descriptions

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#163]
I had a useful conversation with Arvid Aase from Fossil Butte that we should think about a policy for. Nothing to worry about until after Hack-a-Thon, but want to get this in before I forget it.

Let's say that you have a compound leaf, and the terminal leaflet looks very different from the lateral leaflets. For example, the terminal leaflet could be palmately veined and the lateral leaflets pinnate. And whichever it is will propagate differences throughout the description. There are two ways to handle this. First, we could instruct users to create separate descriptions for the two types of leaflets (e.g., "Platanites raynoldsii terminal leaflet" and "Platanites raynoldsii lateral leaflet"). Not sure how this would display for the OTU description, though. Would they just get lumped into a composite description, or is it possible to hold them separate? Alternatively, we could have users create a single description, based on multiple specimens, that chooses multiple character states. This is somewhat less informative, as particular character states may be tied together. For example, leaves that sometimes are lobed and sometimes are not deeply incised enough and so would be considered toothed, whereas the lobed specimen would be untoothed.

**Comment by ecurrano** [comment]
@doricon : we should add discussion of this to the best practices document that we've started.

**Comment by doricon** [comment]
@ecurrano Yes, this would be great for that best practices doc! Probably won't be a one-size-fits-all solution. 

A thought off-hand: 
There is no limit to the number of descriptions/schemas that can be associated with specimen(s) and thus OTUs. So, you don't actually have to lump character states under one description regardless of whether the leaves are one or more specimens. You can create a description node "terminal leaflet MLA" and fill that out, then make another description node for "lateral leaflet MLA"  and fill it out. Those descriptions can belong to one specimen (if both types of leaves are preserved on one specimen) or separate specimens that are all assigned to the same OTU. I think it will work great!
