### ISSUE TITLE
Can't delete states in MLA schema due to blocking relationships

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#167]
Four states need to be deleted from the MLA prior to HackAThon, they are not valid. Maybe I'm just doing it wrong, but I can't get them to delete due to blocking relationships. 

Please delete these four states:
- **absent**, listed under MLA: Veins/Secondary Veins/Intersecondary Veins
- **present**, listed under MLA: also listed under Veins/Secondary Veins/Intersecondary Veins
- **absent**, listed under MLA: Veins/Higher Order Veins/Freely ending veinlets
- **present**, also listed under MLA: Veins/Higher Order Veins/Freely ending veinlets

**Comment by doricon** [comment]
Update: they are deleted now. There were a couple character instances that used those states, which we deleted now too. Closing this issue.
