### ISSUE TITLE
Maximum/minimum interval - collection node

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#168]
I see these fields are grayed out in the data entry form. Assuming this is not going to be ready for the Hack-a-Thon, should we ask people to enter this information in the Notes for updating later?

**Comment by ecurrano** [comment]
I am an IDIOT. I missed the dropdown above to select a time scale. Sorry everyone.

**Comment by aazaff** [comment]
We will never forget and never forgive.

In all seriousness, I do think at some point we should consider curating this list a little. Quite a few silly ones like Custom Cosuna and Scotese.

**Comment by ecurrano** [comment]
Yes, definitely on curating the list. I know this might pain Doug, but the Martian entries are probably also not needed. I'd keep a lot of the marine ones since they may be needed for pollen data.

**Comment by ecurrano** [comment]
Also, I really like the way this was implemented.

**Comment by aazaff** [comment]
There should also be a check that the older intervals is always actually older than the younger interval.

**Comment by doricon** [comment]
Agreed, this is a really nice improvement - I ran across it earlier today and was impressed 🙂



Dori L. Contreras, Ph.D.

Curator of Paleobotany
Perot Museum of Nature and Science

E  ***@***.******@***.***>

P  214.756.5783



[pastedGraphic_1.png]<http://www.perotmuseum.org/>



2201 N. Field Street, Dallas, TX 75201  |  perotmuseum.org

[pastedGraphic_2.png]<https://www.facebook.com/PerotMuseum/>

[pastedGraphic_3.png]<https://twitter.com/PerotMuseum>

[pastedGraphic_4.png]<https://www.instagram.com/perotmuseum/>





________________________________
