### ISSUE TITLE
Create image of latest schema map

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-dev#169]

**Comment by NoisyFlowers** [comment]
![PBOT-SchemaMap-08-01-23](https://github.com/paleobot/pbot-dev/assets/12547812/7a822f59-26f6-49a4-a22d-439bc64f9ea1)

**Comment by NoisyFlowers** [comment]
For clarity, this map omits soft-delete nodes and relationships.

Presenting this map statically like this, it's kind of a mess. If you want to view it dynamically, you can run 

> call db.schema.visualization()

in Neo4j Browser

**Comment by doricon** [comment]
Sweet, thanks Doug! This is exactly what I was hoping to see. I am making a viewer-friendly schematic for major nodes in ppt now.
