### ISSUE TITLE
Can't make people nodes

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#172]
We can no longer add new people nodes. Here is a screenshot of the error message. It says "Error: req is not defined"
![Screen Shot 2023-08-02 at 12 35 16 PM](https://github.com/paleobot/pbot-dev/assets/72828382/619e9d72-475c-4c30-b992-bb2316321cc5)

**Comment by ecurrano** [comment]
And Claire tried this repetitively with adding each optional field individually and in tandem and got this error message, too.

**Comment by NoisyFlowers** [comment]
This is fixed in paleobot/pbot-api@2fd1b2c4436efaed62172a62ab90daf62081495c
