### ISSUE TITLE
Collection node field edits

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#176]
Under Optional Fields, Age: replace "Notes on geographic age" with "Notes on age information". Also, allow multiple lines for this text box as it gets more filled.

Under Optional Fields, Geographic: allow multiple lines for the "Notes on geographic information" text box as it gets more filled.

Under Optional Fields, Geologic: allow multiple lines for the "Additional description of lithology" and the "Notes on environment" text box as it gets more filled.

Under Optional fields: Collecting: allow multiple lines for the "Notes on collection methods" text box as it gets more filled.

**Comment by clairecleveland** [comment]
Also the following fields under Image node:

Credit
Caption

**Comment by NoisyFlowers** [comment]
One problem per issue, please.

**Comment by NoisyFlowers** [comment]
The Collection changes are in paleobot/pbot-client@fcba8110dcbd676f77ff703c94268af8369a10c3
