### ISSUE TITLE
Hardwood Schema

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#18]
@NoisyFlowers 

As an FYI, here is another example schema similar to the "Manual of Leaf Architecture" but for wood.

https://insidewood.lib.ncsu.edu/menu/type/FH;jsessionid=E07zYQdlbjLOn6nzZf6pvUKuErugr5FYeYpyLa6E?1

We might want to enter this into the database as another example schema.

**Comment by aazaff** [comment]
I believe it was determined in the last meeting that Claire and/or Rebecca were going to handle this, as well as some sort of fungus schema?

**Comment by clairecleveland** [comment]
Should we close this out now that we have new schemas coming in from the groups? I don't think we'll be recreating the inside wood database (wood.lib.ncsu.edu).

**Comment by aazaff** [comment]
Sure
