### ISSUE TITLE
Edit Specimen Parts Preserved/Preservation Mode: Can not add/delete additional/extra states--Error returned

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#180]
I tried delete Cuticle from Specimen: Hack-A-Thon Specimen 230808.CC.2 and got error message below.
Also, tried to add Body to Parts Preserved and got same message.

Error: Cannot read properties of undefined (reading 'includes')

**Comment by ecurrano** [comment]
I also got a WEIRD error message when I tried to edit a collection (I was removing a preservation mode).
![Screen Shot 2023-08-02 at 2 00 14 PM](https://github.com/paleobot/pbot-dev/assets/72828382/51ed88eb-ac27-45bf-855b-59734a05f23e)

**Comment by clairecleveland** [comment]
Actually, we can not edit anything on specimen node.

**Comment by ecurrano** [comment]
I discovered that my specific problem with the collection edit is that I had quotation marks in the notes fields. We do need to be able to use these in notes so that people can add quotes directly from the publication.

**Comment by NoisyFlowers** [comment]
One problem per issue, please.

**Comment by NoisyFlowers** [comment]
When we changed Specimen to inherit group from Collection, I overlooked some logic in the api server that expected a groups param from the client. 

This is fixed in paleobot/pbot-api@07ee6ffbb51fcf0e83eb41d4b1b9138a4b79e2e6

**Comment by clairecleveland** [comment]
Thank you Doug!
