### ISSUE TITLE
Editing Quantity States in Character Instances--lose quantity when edit

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#182]
When you edit a quantity state in Character Instances, you lose the quantity. For example, I just wanted to edit the order number. When I saved it I realized I had also lost the quantity state. Please make it so the quantity value is retained when pulling up the edit window.

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@fa62877e989bc631e7053c8b7a999e8a6fc2c1e4
