### ISSUE TITLE
It's not a state, but still is import as recorded data

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#185]
Andrew and Doug, if you read this, skip to last paragraph first.

We have had lots of conversations about states and how strict we should be with them. Totally get that we want to be scientifically accurate in what we call states. Also totally get that this is preventing us from recording other important information...so far.

One thing to consider is that PBot schemas are data entry tools, not treatises. Precedent has been set (MLA) that the schema tool is not as particular about recording states and non-state information. However, that doesn't mean we have to follow a loose precedent. So...

What if we use something like check boxes for non-state information such as not observed, not-applicable, indeterminate? Those node properties can be identified as not states in reports (based on their name) but still be gathered within the character state data for reporting.

One option is to have check boxes at the character level, in some cases only part of the state hierarchy can be observed while the fine detail is not observed. So we need to think this out. How can we implement "checkbox" in the Create character instance box universally--so all in one place/less work for Doug. 

Areolation might be an example to think about. You're in the Create Character Instance: Areolation box. You can tell areolation is present, but have so little of it and can't pick a particular substate. Could the user select present and click the indeterminate "checkbox" which would be interpreted as reporting researcher confirms that areolation is present but detail below that is indeterminate on that specimen?

Feedback, other ideas? This issue needs to be addressed in the current implementation of PBot AFTER HackAThon, but in a way that won't drive Andrew and Doug batty :)

**Comment by doricon** [comment]
I am closing this as there have been many conversations and changes since this.  User testing and experience will likely guide whether we need to add more functionality for this in V2 or V3!
