### ISSUE TITLE
Apparently, ORCIDs can have an X in the last digit

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-dev#188]
I dunno wtf

**Comment by aazaff** [comment]
Maybe just switch to a charlength check? They should always be the same length?

**Comment by NoisyFlowers** [comment]
The last digit in an orcid is a checksum of the other digits that can take on a value of 0..10. 10 is represented by X.

I changed the validation regex to allow X. I also added verification of the checksum.

This is in 
paleobot/pbot-client@9d118a0b8dfe1a235e750f41a4145c480d7614fd
paleobot/pbot-client@a0cc04d8043d6fbefdc2c359cba47e2a83734422

**Comment by NoisyFlowers** [comment]
Merged to master and deployed to dev and stage
