### ISSUE TITLE
Botany team clean up duplicates created during HackAThon

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#191]
Botany team to send email to HackAThon participants to tell them to stop entering data. Then botany team will clean up duplicates created during HackAThon. Once finished, send email to tell HackAThon participants to resume entering data with instructions must check to ensure not entering duplicates.

**Comment by ecurrano** [comment]
We have a newer issue that lists all the duplicates.

**Comment by aazaff** [comment]
#233
