### ISSUE TITLE
A public OTU must have a public holotype Specimen

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-dev#199]

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@cb1a6a1b37a52c2931371436063b1557279032fe
paleobot/pbot-api@c53edb0a09c894592ef883f5ad4c55d516904c70

**Comment by doricon** [comment]
I know we closed this, but I just wanted to note somewhere that we had an issue raised by a participant that they legacy data they were entering did not designate a holotype, and thus they had trouble entering that field. This makes me wonder if we need to be less strict about requiring a holotype specifically. If we don't require holotype, then this public holotype for a public OTU requirement will have to change to at being at least one public identified specimen.
