### ISSUE TITLE
Color code Explore vs Workbench top bar

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#205]
Explore keeps the Green aesthetic

Workbench gets a pleasing shade of gold/yellow. 

Easily helps people know what side they are on :)

**Comment by doricon** [comment]
I just realized our interface top bar is grey. Maybe grey vs green. or something. everything grey except the top bar?

**Comment by NoisyFlowers** [comment]
Limit green to Workbench only, not intro screen.

This is in 
paleobot/pbot-client@900947df99181b129fea339e6b505caf5e542503

merged to master and running on dev and stage
