### ISSUE TITLE
Search Reference by author

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#207]
In the Reference searches within the various data entry forms (the magnifying glass), is it possible to also search by author? Authors is oftentimes the first thing you'd think of when trying to find a reference.

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-client@869723231b1ea46b7c35f1e5ed016dc7225e624d
paleobot/pbot-client@cda3bf44b71c4febc48b35dec30328b27187a18d

Merged to master, deployed to dev. Not yet deployed to stage.

**Comment by NoisyFlowers** [comment]
Deployed to stage (prod).
