### ISSUE TITLE
Rotate image after upload

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#209]
Possible to rotate image after upload?

**Comment by aazaff** [comment]
Like automatically or you mean by the uploader? Can't we ask uploaders to handle this themselves?

**Comment by ecurrano** [comment]
I think the ask was for there to be a PBot function to rotate images. I think this is low priority for PBot v. 1.0 given everything else we need to do, but several people did think this would be useful.

**Comment by NoisyFlowers** [comment]
I dunno. Pbot is not an image processing tool. Seems like some pretty heavy fluff.

**Comment by aazaff** [comment]
I concur this is extremely low priority in the scheme of things.

**Comment by aazaff** [comment]
I also want to clarify though I think they just mean a 2D rotation, not something 3d.

**Comment by ecurrano** [comment]
I also concur that this is low priority. The community asked, and it might be nice to have, but we have so many other more important tasks.

**Comment by ecurrano** [comment]
I am going to close this to reduce the clutter on the issues page.
