### ISSUE TITLE
Add italics to report fields where need in the same way that PBDB has done

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#213]
This is an observation- entering info in description is lagging pretty hardcore with all the users on. Its two states behind populating (hard to see if it really got what I clicked). (CR) UPDATE: lag continues but if you’re adding two states (one with order 1 and another with order 2, and you haven't waited the requisite 15 seconds to satisfy the lag, you will enter the second state with the order defaulting to one (assuming the second entry doesn't see the one in the order from the first state).

Response from Mark Uhen: PBDB does not include text in italics, but it does know to italicize genus and species names when it presents them.

**Comment by aazaff** [comment]
There seems to be two issues/comments jammed into one? Anyway as for italics this is effectively duplicated with #136 #135
