### ISSUE TITLE
Add node diagram flow chart to workbench page

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#216]
Hackathon participants suggested adding a node diagram-based workflow to the workbench homepage, possibly with relationship examples. Two reasons:

(1) Many people find the workflow non-intuitive (even though they understand our reasoning for the order of operations), and thus something to help them keep track on-screen would be nice. 

(2) The various relationships between nodes (particularly, description-specimen-OTU) are best understood by seeing the diagrams and examples.

**Comment by doricon** [comment]
Also consider additionally changing the workbench toolbar order to reflect entry order

**Comment by aazaff** [comment]
The current workbench order was recently revised in #139. Best to finalize and not repeat effort.

**Comment by ecurrano** [comment]
I am going to close this issue because 1) we don't have time to repeat effort on finalizing the workbench toolbar in v1, and 2) our how-to static page will handle this.
