### ISSUE TITLE
review and expand search query fields

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#224]
Couldn't find an existing issue for this (but it might be somewhere - if so, apologies!). I know this is all included in our upcoming Explore build-out

Search query forms should be updated to include missing fields. Some that were noted during the hackathon: 
-search by author
-OTU search is missing the name field

**Comment by doricon** [comment]
Just saw that some of this has already been done - Yay!

**Comment by aazaff** [comment]
tangential to #136

**Comment by NoisyFlowers** [comment]
OTU query updated with all fields including specimen and synonym relationships. This is in
paleobot@pbot-client@a614c0d2d929417a51f1b420ef940d60fd055b89
paleobot@pbot-client@48d4aa22ca4d231b30766657eb9d2244f7cbf4f1
paleobot@pbot-client@c4097d14d10f347d2881056d55a01a6a21d8cf9b
paleobot@pbot-client@5b7156e0198ef2184af6ea69febf2199cb1061e2
paleobot@pbot-client@2688dd4f9f4496f173d63418b94530e669d0863d
paleobot@pbot-client@8731e131e5da50da335e9308af3e0c05ce626d97
paleobot@pbot-client@f7dc08a78bb003763a1da184c93267544fc7342d

**Comment by NoisyFlowers** [comment]
Collection query updated with all fields including specimen and synonym relationships. This is in
paleobot/pbot-client@857ae2f99d33fdc1996bd836f958d9cd7b45d164
paleobot/pbot-client@6051faefd27d80613d5bfe8c6d82dcbf09f7759e
paleobot/pbot-client@23ebe822200ec5d5dbb1ce9067010f7e6103507a
paleobot/pbot-client@b7f7197d891471b571ee32e8c84006e1f21c5b41
paleobot/pbot-client@

**Comment by NoisyFlowers** [comment]
Specimen query updated with idigbio stuff, repository, and reference, description, identified, and type relationships. This is in
paleobot/pbot-client@b8fa39455687c970241e1ef258999f7d3cfd3ff1

**Comment by NoisyFlowers** [comment]
Schema query logic for purpose, reference, and specimen. Not sure how handy that last will be, but it seemed cool to say "show me the Schemas used in describing this Specimen". This is in 
paleobot/pbot-client@d24352aa5e7c6b1ae227d39f9c090c48fa12e14e
paleobot/pbot-client@7f580a12d8df66cab1bbbe9e67bf95696bf8e996
paleobot/pbot-client@1360ca768debda6c183beb2aea7e79b12ecc0f46

Note that I am using ReferenceSelect for the reference logic, bypassing ReferenceManager. In the Schema mutate form, I use ReferenceManager, passing params to indicate that it should only allow a single entry. I'm not sure why I did it that way. Elsewhere in these query updates, I go directly to the XSelect component. This means there is some inconsistency in presentation between the query form and the mutate form. Potato/Potahto, the end result is the same. I might modify one or the other, but I can't decide which. If I go with the RefManager approach, should I do this everywhere? Yuk.
