### ISSUE TITLE
Add optional fields to descriptions to show "lineage"

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#226]
This is a note from Andrew during hackathon. Need to expand this issue with explantation

**Comment by aazaff** [comment]
I don't remember what this means. Closing as nonsensical.

**Comment by doricon** [comment]
Lol. Maybe this was to help with the taxonomy issues of newer descriptions by other authors, etc.



Dori L. Contreras, Ph.D.

Curator of Paleobotany
Perot Museum of Nature and Science

E  ***@***.******@***.***>

P  214.756.5783



[pastedGraphic_1.png]<http://www.perotmuseum.org/>



2201 N. Field Street, Dallas, TX 75201  |  perotmuseum.org

[pastedGraphic_2.png]<https://www.facebook.com/PerotMuseum/>

[pastedGraphic_3.png]<https://twitter.com/PerotMuseum>

[pastedGraphic_4.png]<https://www.instagram.com/perotmuseum/>





________________________________
