### ISSUE TITLE
Change toolbar name from Taxa (OTU) to OTU (species)

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#230]
Change toolbar name from "Taxa (OTU)" to "OTU (species)"

alternative would be "OTU (taxon)" if botany team prefers?

**Comment by aazaff** [comment]
Heavily requested at workshop.

**Comment by aazaff** [comment]
Marked as question because we should let doug now exactly what we want it changed to.

**Comment by ecurrano** [comment]
I like "OTU (species)" since we discussed the possibility of eventually allowing higher taxon OTUs (next grant cycle).

**Comment by doricon** [comment]
Taxon (OTU) would be flexible for however we end up handling various ranks. 

Decide this Wed after discussion of ranks (Sept 27).

**Comment by doricon** [comment]
Did this actually get done? I can't check it in dev.

**Comment by aazaff** [comment]
I don't know, but presumably whatever it is currently is what we wanted it to be. It's the type of thing that should have been encapsulated in #290 #291
