### ISSUE TITLE
Hyperlinks to specimen and OTU on the Explore results

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#231]
On some record pages there are hyperlinks to see the specimen or OTU. 
(eg OTU records have hyperlinks to specimens; and Collection records have hyperlinks to specimens)

Can these links default to showing the images, desciptions, etc (all the checkboxes on the search query)

**Comment by aazaff** [comment]
I think this is very specific and would be encapsulated in the broader query rework.
