### ISSUE TITLE
PBDB validation icon

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#232]
Botany team decide what we should replace the magnifying glass for searching whether collections or references are in PBDB. Then Doug should implement.

**Comment by NoisyFlowers** [comment]
I'm drawing icons from here: [https://mui.com/material-ui/material-icons/](https://mui.com/material-ui/material-icons/)

If you see anything there that you like, let me know.

**Comment by NoisyFlowers** [comment]
For now, I've changed the icon to the ManageSearchIcon.

This is in 
paleobot/pbot-client@0f24c279b2c2aebb4cc984a3d0c93fa5470ae41d

**Comment by aazaff** [comment]
Nobody had any feedback.
