### ISSUE TITLE
Duplicate People

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#233]
Here are the duplicate people. We need to figure out how to merge the data assigned to the duplicate nodes and "delete" one of them.

Daniel I Axelrod and Daniel I Axelrod
Claire Cleveland and Claire Cleveland--Duplicate
Andrew Flynn and Andrew G Flynn
Bonnie Fine Jacobs and Bonnie F Jacobs--Duplicate, do not use
Alex Lowe and Alexander J Love
Ian M Miller and Ian M Miller
Claudia Richbourg and Claudia Gail Richbourg
Caroline Stromberg and Caroline A.E. Stromberg
christopher west and Christopher K. West
Paige Kathryn Wilson Deibel, Paige Wilson Deibel, and Paige Wilson Deibel
Andrew Zaffos and Andrew Zaffos

**Comment by aazaff** [comment]
I'm switching this from enhancement to bug in the sense that this was only allowed to happen because we messed up.

**Comment by ecurrano** [comment]
Could not duplicate on 2/7/24

**Comment by NoisyFlowers** [comment]
In researching how to deal with the Claire case and maintain relationship values, I stumbled across the apoc.refactor routines (https://neo4j.com/labs/apoc/4.1/overview/apoc.refactor/apoc.refactor.to/). Rather than creating new relationships, as the cypher in the previous comment would, the routines apoc.refactor.to and apoc.refactor.from reassign the endpoints of existing relationships. 

This solves the problem with the Claire case. I may also use it for all the others as well.

**Comment by NoisyFlowers** [comment]
New cypher, using apoc.refactor routines:

Daniel I Axelrod and Daniel I Axelrod 
	7020ce61-d6d1-4482-80c0-51629ddd7b91 is correct, has an AUTHORED_BY
	a1566637-0654-4c69-99a3-9f79c1765378 has a blank at the end of "Axelrod ", is unregistered, has an AUTHORED_BY and a HAS_IDENTIFIED
	proposed cypher:
```
		MATCH
			(p_right:Person {pbotID:"7020ce61-d6d1-4482-80c0-51629ddd7b91"}),
			(p_wrong:Person {pbotID: "a1566637-0654-4c69-99a3-9f79c1765378"})<-[ab_rel:AUTHORED_BY]-(),
		CALL apoc.refactor.to(ab_rel, p_right)
		YIELD input, output
		RETURN input, output;	
		
		MATCH
			(p_right:Person {pbotID:"7020ce61-d6d1-4482-80c0-51629ddd7b91"}),
			(p_wrong:Person {pbotID: "a1566637-0654-4c69-99a3-9f79c1765378"})-[ab_rel:HAS_IDENTIFIED]->(),
		CALL apoc.refactor.from(ab_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "a1566637-0654-4c69-99a3-9f79c1765378"}),
		DETACH DELETE
			p_wrong
```	
	
Claire Cleveland and Claire Cleveland--Duplicate
	DUPLICATE (30283908-5eb8-4f84-8020-99f4e9451f09) is registered, busy
	Cleveland (3bc1127f-3deb-4862-b72c-8a61402f36a7) is registered, busy
	proposed cypher:
```			
		MATCH
			(p_right:Person {pbotID:"3bc1127f-3deb-4862-b72c-8a61402f36a7"}),
			(p_wrong:Person {pbotID: "30283908-5eb8-4f84-8020-99f4e9451f09"})<-[eb_rel:ENTERED_BY]-(),
		CALL apoc.refactor.to(eb_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		MATCH
			(p_right:Person {pbotID:"3bc1127f-3deb-4862-b72c-8a61402f36a7"}),
			(p_wrong:Person {pbotID: "30283908-5eb8-4f84-8020-99f4e9451f09"})-[m_rel:MEMBER_OF]->(),
		CALL apoc.refactor.from(m_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "30283908-5eb8-4f84-8020-99f4e9451f09"}),
		DETACH DELETE
			p_wrong
```	
	

Andrew Flynn and Andrew G Flynn
	Andrew G. Flynn (4521285d-a1d1-4f62-83c7-9542fbf9594f) is registered and busy. 
	Andrew Flynn (e36874dd-3b27-4f06-95ba-c3ea6be4fb20) has no important relationships.
	proposed cypher:
```
		MATCH
			(p:Person {pbotID:"e36874dd-3b27-4f06-95ba-c3ea6be4fb20"})
		DETACH DELETE 
			p
```

Bonnie Fine Jacobs and Bonnie F Jacobs--Duplicate, do not use
	Bonnie F Jacobs--Duplicate, do not use (bf892bd5-ee7d-4693-8868-443085b3320c) is unregistered, has two AUTHORED_BY
	Bonnie Fine Jacobs (53f25bc5-3f6b-4446-9b0b-7cf066d8a50a) is registered and busy
	proposed cypher:
```		
		MATCH
			(p_right:Person {pbotID:"53f25bc5-3f6b-4446-9b0b-7cf066d8a50a"}),
			(p_wrong:Person {pbotID: "bf892bd5-ee7d-4693-8868-443085b3320c"})<-[ab_rel:AUTHORED_BY]-(),
		CALL apoc.refactor.to(ab_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "bf892bd5-ee7d-4693-8868-443085b3320c"}),
		DETACH DELETE
			p_wrong
```	
	
Alex Lowe and Alexander J Lowe
	Alex Lowe (9a473ea1-2431-4400-b835-ca39015e565d) has no important relationships
	proposed cypher:
```
		MATCH
			(p_wrong:Person {pbotID: "9a473ea1-2431-4400-b835-ca39015e565d"}),
		DETACH DELETE
			p_wrong
```	
	
Ian M Miller and Ian M Miller
	b099e601-5303-4c0a-9c28-7649a271abab is unregistered, has an email address, two AUTHORED_BY
	036fb9fa-fdea-46cc-b7d5-989669c4806c is unregistered, has no email address, one AUTHORED_BY
	proposed cypher:
```		
		MATCH
			(p_right:Person {pbotID:"b099e601-5303-4c0a-9c28-7649a271abab"}),
			(p_wrong:Person {pbotID: "036fb9fa-fdea-46cc-b7d5-989669c4806"})<-[ab_rel:AUTHORED_BY]-(),
		CALL apoc.refactor.to(ab_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "036fb9fa-fdea-46cc-b7d5-989669c4806c"}),
		DETACH DELETE
			p_wrong
```	
	
Claudia Richbourg and Claudia Gail Richbourg
	Claudia Gail Richbourg (8023ba2c-0df2-415c-b72c-0ce7b011effb) is registered, 
	Claudia Richbourg (67d3c4df-c053-44e3-83be-b227e311216e) is unregistered, MEMBER_OF "Ellen's test group"
	proposed cypher:
```		
		MATCH
			(p_right:Person {pbotID:"8023ba2c-0df2-415c-b72c-0ce7b011effb"}),
			(p_wrong:Person {pbotID: "67d3c4df-c053-44e3-83be-b227e311216e"})-[m_rel:MEMBER_OF]->(),
		CALL apoc.refactor.from(m_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "67d3c4df-c053-44e3-83be-b227e311216e"}),
		DETACH DELETE
			p_wrong
```			
	
Caroline Stromberg and Caroline A.E. Stromberg
	Caroline Stromberg (4957b5fb-a5c3-4d3a-8d1d-882c8ea186ee) has one AUTHORED_BY
	Caroline A.E. Stromberg (7e4a005d-55c0-4e38-950c-94613b7c0a3f) has one AUTHORED_BY
	proposed cypher:
```		
		MATCH
			(p_right:Person {pbotID:"7e4a005d-55c0-4e38-950c-94613b7c0a3f"}),
			(p_wrong:Person {pbotID: "4957b5fb-a5c3-4d3a-8d1d-882c8ea186ee"})<-[ab_rel:AUTHORED_BY]-(),
		CALL apoc.refactor.to(ab_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "4957b5fb-a5c3-4d3a-8d1d-882c8ea186ee"}),
		DETACH DELETE
			p_wrong
```	
	
christopher west and Christopher K. West
	christopher west (04022c00-c6b1-44db-8696-9c5eed49c9b9) has no important relationships
	Christopher K. West (0227cc63-fccd-47da-a933-e6eacf2daa27) is registered
	proposed cypher:
```
		MATCH
			(p_wrong:Person {pbotID: "04022c00-c6b1-44db-8696-9c5eed49c9b9"}),
		DETACH DELETE
			p_wrong
```	
	
Paige Kathryn Wilson Deibel, Paige Wilson Deibel, and Paige Wilson Deibel
	Paige Kathryn Wilson Deibel (2a5a71e0-e59f-4b72-83b9-0e8b7cfac07a) is registered and busy
	Paige Wilson Deibel (6563e0f9-8de9-4c57-b903-953bbd7739a2) has no important relationships
	Paige Wilson Deibel (fcc582a4-316b-48fc-94fe-d443a9004a5e) has no important relationships
	proposed cypher:
```
		MATCH
			(p_wrong:Person {pbotID: "6563e0f9-8de9-4c57-b903-953bbd7739a2"}),
		DETACH DELETE
			p_wrong

		MATCH
			(p_wrong:Person {pbotID: "fcc582a4-316b-48fc-94fe-d443a9004a5e"}),
		DETACH DELETE
			p_wrong
```	
	
Andrew Zaffos and Andrew Zaffos
	Andrew Zaffos (7e741261-2f00-4d8a-bfad-916c7b2e7ad7) is registered, has no orcid, MEMBER_OF several groups
	Andrew Zaffos (c474f2be-3c9f-4333-a176-fccdfab37622) is unregistered, has an orcid, MEMBER_OF two groups
	proposed cypher:
```		
		MATCH
			(p_right:Person {pbotID:"7e741261-2f00-4d8a-bfad-916c7b2e7ad7"}),
			(p_wrong:Person {pbotID: "c474f2be-3c9f-4333-a176-fccdfab37622"})-[m_rel:MEMBER_OF]->(),
		SET
			p_right.orcid=p_wrong.orcid
		WITH
			p_right, p_wrong, m_rel
		CALL apoc.refactor.from(m_rel, p_right)
		YIELD input, output
		RETURN input, output;	

		//Verify this worked, then
		MATCH
			(p_wrong:Person {pbotID: "c474f2be-3c9f-4333-a176-fccdfab37622"}),
		DETACH DELETE
			p_wrong
```
