### ISSUE TITLE
Quantitative characters

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#234]
Quantitative characters are now being enforced that an integer must be entered. Did this change since hte Hack-a-Thon. I thought people were able to be very fluid about what gets typed in L:W ration (MLA schema), but now I am trying to enter a new description and I get the error message. If this remains, we will need to record the MLA L:W schema such that we have categories of <1:1, 1.1-1.9:1, etc.

**Comment by ecurrano** [comment]
Note this will also be a problem for number of basal veins in the MLA. I think the answer here is to recode with options 1,2,3,4,5,6,7,>9. This will be something people search on quite a lot, I think, and having the options might be a quicker fix than figuring out how to do quantitative searches?

**Comment by aazaff** [comment]
I'm not sure why it got changed, but I think we should revisit this in next meeting. There are pros and cons in both respects. One solution may be to add a couple of different states other than "Quantity".

**Comment by NoisyFlowers** [comment]
I am not able to reproduce this problem. Can enter values like "50:1" without error.

**Comment by aazaff** [comment]
@ecurrano bouncing this back to you to see if you can reproduce it.

**Comment by ecurrano** [comment]
I found my problem. I am entering things in the Order field, rather than the Quantity field. Partially me being a doofus, but I think we could improve clarity in the form. Options: 1) add the header "Enter value here" above where you enter quantity? or 2) remove the word Quantity where you enter the text. See screenshot
![Screen Shot 2024-02-21 at 4 26 54 PM](https://github.com/paleobot/pbot-dev/assets/72828382/0cb7f6c2-2537-4177-9614-d12028a87580)
