### ISSUE TITLE
PBot Users, People Nodes, Groups

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#238]
When Ellen goes to enter people in a group, she sees a big list of people who did not attend the Hack-a-Thon and are unlikely to have PBot accounts. Example: Scott Wing. Interestingly, Dori does not see Scott Wing as an option to add to groups.

From Andrew: One possible source of bugs is when I created the very very first pilot version of the database, I put in emails for Persons (well BEFORE we had an account system). So Scott may have an email even though he doesn’t have an account? Or maybe that was cleaned up at some point already.

**Comment by NoisyFlowers** [comment]
There is currently no filtering of Person nodes in Person select lists. If there's a node, that name will show up in the list, registered or not.  

I'm not sure there's a need for filtering. I don't see a problem with adding a Person who is not registered to a Group. A person setting up a Group can add the people they want without worrying about getting them registered. Later, when somebody previously unregistered then registers, they will already be in the Group.

**Comment by NoisyFlowers** [comment]
That said, if we decide we'd rather only show registered users, that's certainly possible.

**Comment by doricon** [comment]
IMO I think it's fine how it is now (all person nodes are possible). Doug makes a good point that this will help make it smoother for if someone hasn't registered yet and you need to put them in a group.
