### ISSUE TITLE
OTU specimen requirement change

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#242]
Currently an OTU requires a holotype. We have run across the complication that not every valid description has a holotype specimen designated or enter-able (particularly old literature). Two options: 

(1) OTUs require a supporting specimens, but it does not have to be a explicitly a holotype (or even a type).  
(2) Under the type and holotype selection drop-downs (which populate from the identified specimens), have an option for "type not available/designated". 

*note: consider effects on the public/private OTU requirement. Need a corresponding change so that a public OTU is supported by at least one identified specimen as opposed to specifically the holotype.

**Comment by doricon** [comment]
Update following 9/27/2023 meeting: 

Shift the requirement for OTUs to the type/example specimens, rather than the holotype.

**Comment by aazaff** [comment]
move to #246
