### ISSUE TITLE
Add field for link to Fossil Plant Names registry

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#244]
https://www.plantfossilnames.org/

This is the website for registered valid fossil plant names. Taxa are given a registry number for the taxon and the nomenclatural act that supports it. The data is vetted. This will soon be a requirement for publishing new names (like it is for Zootaxa). Support/interoperability would be really good. 

In the optional part of the OTU form:
Add field beside the genus field for the registry link to genus name. 
Add field beside the specific epithet for registry link to species name. 
Also provide a link to (https://www.plantfossilnames.org/) like what was done for the PBDB link below PBDB parent taxon. 

*in the future would be great to be able to pull data from the Plant Fossil Names database (that would be a distant V3 thing I would imagine)

**Comment by doricon** [comment]
Please before more data entry opens up :)

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@51f7efca0df35e9cfb82dbc3d87ffe5bbc0fd031
paleobot/pbot-client@af6bb53ad60009cdae65a2fd7902eda6983847fd
paleobot/pbot-client@837b34360b5ed08dccb672ecd5d32000584f4f3b
paleobot/pbot-client@f7c7289005aa5914f299e115bc6ae2506cdad425

not yet merged to master

**Comment by NoisyFlowers** [comment]
Merged to master and deployed to dev and stage
