### ISSUE TITLE
Add free-text field for pasting descriptions on the description node

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#245]
Requested at Hackathon and is a good idea for capturing difficult data. 

On the description node form, under the optional fields, add a free-text field above the Notes field for "Written description"

This is an option for pasting the text of a description. It is particularly useful for older literature where the schema character entry is basically a translation of the original text description. This faithfully preserves the original author's words.

**Comment by doricon** [comment]
Please before more data entry opens up :)

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-api@d1788153ab50c0ebe99b0fa8c7982ab0c46b38f5
paleobot/pbot-client@426ab89462d199220de607a635a5ecda4a24bcc4
