### ISSUE TITLE
Holotype / Exemplar specimen selection update

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#246]
For the selection of types and holotype specimens, make each have a dropdown to select which kind you are entering and then select the specimens from the list. 

Selection for Types: dropdown for either Types or Example specimens
Selection for Holotype: dropdown for either Holotype or Exemplar specimen

**Comment by aazaff** [comment]
As a temporary solution we are going to make holotype NOT REQUIRED in the OTU form and fix any indirect implications of that - e.g., "Include Holotype Description" checkbox in search form.

Longer term, we will split OTU node into two types - mirroring how we split references into multiple types - one for "true" pbot style OTUs and one for legacy OTUs or formal taxonomies.

**Comment by NoisyFlowers** [comment]
Holotype optional is in
paleobot/pbot-api@58ffb950c64e97fbd05dde9551a6e2de11843673
paleobot/pbot-client@9948134d9df55245f3248f6a6ac5f3ac21608c2e
paleobot/pbot-client@ec44b3aff6db44e1c66fef9e6d60be9f66a2f32f

**Comment by aazaff** [comment]
The broader point here is really subsumed into #225
