### ISSUE TITLE
Bulk upload workflow

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#25]
Alex Lowe reached out with an example bulk export of his data. This raises the broader issue of how do we want to support bulk data. (he gave an example CSV, but I did not upload it to Github to protect his privacy)

I'm going to open this for discussion, but broadly speaking we should probably settle on SOME kind of easily interpreted standard that matches the graph structure... so maybe we would CSV's like...

----- | ----- | -----
Sample ID | Character | State
---- | ----- | -----
15 | Apex Angle | Acute
15 | Apex Angle | Obtuse†
15 | Apex Shape | Rounded*

*Rounded is a substate of convex. Just have the user choose the finest level of resolution and we can reverse infer the parent states. (i.e., we already know from the schema that rounded is a child of convex).
†If a specimen has multiple states for the same character, we just enter it twice.

**Comment by ecurrano** [comment]
Just adding a note that I also spoke with Peter Wilf and Gabby Rosetto about this at MPC. Gabby has developed a neat way to use Adobe Bridge to morphotype floras until we have PBot.

**Comment by clairecleveland** [comment]
Should we close this comment in favor of continuing the discussion in Issue#49?

**Comment by aazaff** [comment]
Yes, this is superseded as an issue by #49
