### ISSUE TITLE
Change State Name "quantity" to allow specific name for that state

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#252]
Because the name of quantity states defaults to "quantity" instead of allowing a specific name, it is not possible to have two quantity states listed under a single character. The second entry is rejected because the State "quantity" already exists for that Character. This will become a problem for at least two of the upcoming schemas that include characters such as stomatal dimensions which will include quantities length, width, area, perimeter, etc. Is this a difficult fix that has to be shifted to V2 or is this not such a difficult fix?

**Comment by aazaff** [comment]
It is not a difficult fix and does not need to wait to V2, but has to wait until pbot dev work resumes in winter.

**Comment by aazaff** [comment]
I think @NoisyFlowers had a cogent workaround for this but that wasn't recorded in the issue. I'll try to find it later.

**Comment by NoisyFlowers** [comment]
The proper way to handle the scenario described is to have a stateless super-character "stomatal dimensions" with separate sub-characters for "stomatal length", "stomatal width", etc.
