### ISSUE TITLE
Search results not working - no results 

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#253]
I tried to do some searches via Explore, and when I press submit the page does a little refresh-type thing (like it's trying to do something) but does not return any result. I tried while not logged in and while logged in. I am using the new domain name pbot.paleobiodb.org

**Comment by aazaff** [comment]
I tested every route and got a result eery time. Can you give me some specific search example?

**Comment by aazaff** [comment]
I got on Zoom with Dori. We were able to duplicate the problem on her older version of Safari (11), but it worked every time on her Chrome. It works for Andrew on both Safari (16) and Chrome. 

We've had reports from other users (Ari and Claire) of this same effect, but we don't know what browsers they were using or if that is even relevant.
