### ISSUE TITLE
static content

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#257]
[PBot Participant packet.pdf](https://github.com/paleobot/pbot-dev/files/13591438/PBot.Participant.packet.pdf)

Here is the how-to packet we made for the Hack-a-Thon. We should make this available for people to download on the How to Use PBot page until we have better materials.

There will also be information for the about page. We need to finalize this within the Botany team.

**Comment by aazaff** [comment]
Can we close #236 and #237 merge into this?

**Comment by doricon** [comment]
Yes, we should consolidate the how-to-use instructionals into one issue. We are revising the form instructions over the next week to match the updated field structure (where applicable) and to reflect user feedback from the hackathon. 

We are still not sure of the exact plan for implementing this in PBOT - but will have form-specific word docs/pdfs ready to go shortly! And a revised workflow diagram for folks to follow.

**Comment by aazaff** [comment]
I'm closing this as static issues now make sense on the static repo.
