### ISSUE TITLE
Collection Editing - PBDB check

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#259]
When you edit a collection, you are required to search PBDB again. Maybe not a bad idea, as you might be making a correction that would then cause the collection to match a PBDB collection. But it can be a little annoying to have to do this every time. Just want to make sure we all support doing things this way.

**Comment by aazaff** [comment]
I vote for leaving it annoying.

**Comment by aazaff** [comment]
We are closing this for now, but can revisit the issue in the future if we receive complaints.
