### ISSUE TITLE
Search for external information

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#26]
How will we support searching for external information? For example - the info that is linked through iDigBio, such as repository info or other specimen info that we are not directly storing. 

This came us as a result of discussions in the Paleo Data Happy Hour meeting. Here are the meeting shared notes: https://docs.google.com/document/d/13CtuqsaRFz4n1SBWOvwl2U7UzTNtzaH9-7actrHcXe0/edit

and a recording of the meeting: 
https://drive.google.com/file/d/1rjnESAfX55v-oggNFfirotlQQLE0SqeE/view

**Comment by aazaff** [comment]
This can be handled by making requests to the search APIs of the respective sites - e.g., paleobiodb https://paleobiodb.org/data1.2/colls_doc.html. 

We may want to do some research on this to make sure the i/o is sustainable however.

**Comment by doricon** [comment]
If we do this by searching the APIs of the other sites, does that enable us to display those results in our search results? (apologies if that is a silly question!)

Further, can we combine info sourced from another site and unique info sourced from our site in the same output? For example, if I wanted to search for and display the following: all the OTUs from the Cretaceous in our database along with the museum specimen numbers and museum/repository name for the specimens that support those OTUs.

**Comment by aazaff** [comment]
Yes.
