### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#260]
I cannot edit any nodes in PBot. Below is the screenshot for of what I see for any node.
![Screen Shot 2024-02-05 at 9 24 04 AM](https://github.com/paleobot/pbot-dev/assets/72828382/669ebd76-a5a0-40e0-b562-d03e014579c0)

I get the same error message for all searches, screenshot example below.
![Screen Shot 2024-02-05 at 9 25 28 AM](https://github.com/paleobot/pbot-dev/assets/72828382/e5e819de-1c58-493e-b572-37593cf9f07a)

It also pops up sporadically when I am trying to create new nodes. Example: 
![Screen Shot 2024-02-05 at 9 26 30 AM](https://github.com/paleobot/pbot-dev/assets/72828382/17ad5857-2a6b-4226-ae3e-5d2eb3faa271)

**Comment by ecurrano** [comment]
Screenshots from Chrome devtools. Sorry to not know which are useful. I had the collections node and edit up when I was doing this.
![Screen Shot 2024-02-05 at 9 36 50 AM](https://github.com/paleobot/pbot-dev/assets/72828382/a04f33cb-7c62-4f3c-9006-d638b0d13a49)
![Screen Shot 2024-02-05 at 9 37 12 AM](https://github.com/paleobot/pbot-dev/assets/72828382/276f8481-632d-4d32-8a91-e98bff57a87f)
![Screen Shot 2024-02-05 at 9 37 26 AM](https://github.com/paleobot/pbot-dev/assets/72828382/a02a1c6f-f1d2-4bfa-9d20-7a7cbcf57dca)
![Screen Shot 2024-02-05 at 9 38 36 AM](https://github.com/paleobot/pbot-dev/assets/72828382/7f9541c5-6707-4073-9670-8d94c7b7fa14)
![Screen Shot 2024-02-05 at 9 39 23 AM](https://github.com/paleobot/pbot-dev/assets/72828382/a3923925-89a2-463f-a633-c7e45539f321)
![Screen Shot 2024-02-05 at 9 39 38 AM](https://github.com/paleobot/pbot-dev/assets/72828382/3a876067-30d3-41c1-ad28-e8952c5b9902)

**Comment by aazaff** [comment]
Great use of inspect tool @ecurrano

For the future, probably can always skip the "elements" tab. The most generally useful will be "Console", but network, application, and source can be useful secondarily. I think.

**Comment by NoisyFlowers** [comment]
PM2 was not fully set up and there must have been a reboot recently. The api server was not running.

It's ok now.
