### ISSUE TITLE
Country dropdown in Collections

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#262]
Not working on 2/5 for Ellen. This prevents new collections from being added.
![Screen Shot 2024-02-05 at 3 22 41 PM](https://github.com/paleobot/pbot-dev/assets/72828382/d45c9e39-0756-48ae-8f99-75f14d751cf9)

**Comment by ecurrano** [comment]
Also, check whether the state/province dropdown in the optional fields (geographic) is also broken, or if it just requires Country to work.

**Comment by NoisyFlowers** [comment]
This was an nginx configuration problem.

URL paths /countries and /states are accessed in the client but are hosted in the api server. In a dev environment, routing of http calls to these paths is handled by  a proxy property in package.json. This does not work in the production environment. Instead, the routing must be handled in nginx config. This was missing.

Both are working now, and I've updated the the install procedure in Knowledge Base issue #240.

**Comment by ecurrano** [comment]
@NoisyFlowers : The country dropdown now works for me in http://128.196.196.17/ but not in https://pbot.paleobiodb.org/. I did restart Chrome and am shortly restarting my computer (just as soon as updates are installed)

**Comment by NoisyFlowers** [comment]
I am unable to reproduce this. It is working for me on pbot.paleobiodb.org.

**Comment by ecurrano** [comment]
I cleared my browser history and now it works. I shall file this away in my list of troubleshooting hints.
