### ISSUE TITLE
Problem with editing a collection

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#266]
I have entered some private collections. I am now trying to edit them. They do appear in the dropdown menu, and if I click on them that way, then I can see the complete information to edit. However, if I try using the magnifying glass search, I can get the collection name but then only see blank below that. See screenshot below. Note that when I searched for the collection the same way in Explore, it worked great and I could see everything.
![Screen Shot 2024-02-09 at 2 44 04 PM](https://github.com/paleobot/pbot-dev/assets/72828382/8d8b079b-daf2-4bdb-a0d4-6badbd166436)

**Comment by NoisyFlowers** [comment]
This is fixed in
paleobot/pbot-client@068a3e1822db036a3a4f37f0b5f88cbe911d752f
paleobot/pbot-client@8df67c5d64e79f78d1ff13d48a1ebf29dbf9a3b8

merged to master, running on dev and stage.

This same problem exists for Specimens. I'm going to wait until Monday to look at that with fresh eyes.

**Comment by NoisyFlowers** [comment]
Ignore previous. There are still issues with Collection.

**Comment by NoisyFlowers** [comment]
Ok, fixes for Collection and Specimen are in 
paleobot/pbot-client@6580c0b23df27fe4b85cbba691c16c8e71752127
paleobot/pbot-client@c864485ad3f9466878a5223b391e5e4aea9db91d
paleobot/pbot-client@fb52300b6cd9cc0fab889f4e2221d2bfe0c947ca
paleobot/pbot-client@e873bdb966e0ab88e51df5dac38f6dc10e9941f0
paleobot/pbot-client@73f4dab90ab956ffd890244f3f04266bccc270da

merged to master and running on dev and stage

This was a little hairy, so I'm going to leave this issue open until you have a chance to see if you find any problems.
