### ISSUE TITLE
Description Node, Specimens

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#269]
I created a new description node, "Artocarpus 2 Currano and Wing MLA," and assigned a single specimen "USNM PAL773700." Whenever I edit the node (here, adding Character instances), that specimen gets added again. I am now up to 8 versions of it:
![Screen Shot 2024-02-16 at 2 04 58 PM](https://github.com/paleobot/pbot-dev/assets/72828382/391701fb-655e-4217-aae5-ac07b037e8d5)

**Comment by ecurrano** [comment]
Note that I can delete the excess versions, which I'm doing as I edit this description. I'm entering real data here!

**Comment by ecurrano** [comment]
When I looked the specimen up in Explore, I saw 8 versions of the Description.

**Comment by NoisyFlowers** [comment]
I can't reproduce this in my local test environment. Before I try it on the prod server, is there anything else you can tell me about the occurence? Does the dup specimen get added when you click submit in the popup CharacterInstance dialog box?

**Comment by ecurrano** [comment]
Duplicate specimens are not added when I click submit in the popup CharacterInstance dialog box. Just when I submit the Description Form. The number of times I see the specimen doubles every time I edit the description form and submit. So, the first edit gave me 2, after a second edit I had 4, then up to 8... It does not appear to make a difference how many Groups the description is part of. Just get a doubling every time I submit an edit.

I am playing with description node 3f4fa5e7-6cac-446c-adf5-4db37190b0f5.

**Comment by ecurrano** [comment]
I cannot recreate this issue in dev. Description node 24005ba1-058a-4cd2-bd14-b5966c3255e6 in dev was my attempt, and I've done all the things that made specimens propagate in stage. It's an identical collection, specimen, and description (although I did not enter all character instances), minus me adding "(test)" to node names.

I am still getting specimen duplication in stage for description node 3f4fa5e7-6cac-446c-adf5-4db37190b0f5. If others look at this node, do you also see (now 4) listings of USNM PAL773700?

To see if this is just a mistake I somehow made in the "Artocarpus 2 Currano and Wing MLA" node (3f4fa5e7-6cac-446c-adf5-4db37190b0f5), I created a new description node in stage: Nubbins Currano and Wing MLA (c10a8c9a-862e-4974-9153-26cf4e702d85). On my first attempt to edit the description, I already see a duplication of the specimen.
![Screen Shot 2024-02-21 at 11 22 55 AM](https://github.com/paleobot/pbot-dev/assets/72828382/16eeec73-80ae-4a28-a891-122b817644d1).

So, maybe fixed on dev, perhaps somehow related to #268 's solution?

**Comment by NoisyFlowers** [comment]
Yeah, I really think this is a multiple group thing. It fits the profile of the sort of problem I was worried that might produce. 

Let's see if the problem goes away on stabe/prod once I deploy that fix there.

**Comment by ecurrano** [comment]
Oh, I realize that since these nodes are private, you all might not be able to see them. I've added Doug, Dori, and Andrew now to the two groups I have these descriptions in.

**Comment by ecurrano** [comment]
Also, fingers crossed the problem goes away when the fix gets deployed on stage/prod.

**Comment by ecurrano** [comment]
Note that in stage/prod, this was also a problem for OTUs, with specimen duplication in the Identified specimens field. This problem does not occur in dev, so Doug is amazing!

**Comment by NoisyFlowers** [comment]
Just want to clarify: has this problem gone away on stage/prod? If so, I'll close this.

**Comment by ecurrano** [comment]
Everything works great now. So I'm going to close this.
