### ISSUE TITLE
Description node Notes field error message

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#271]
Error: Invalid input 'r': expected 'n/N' (line 53, column 66 (offset: 1890)) " baseNode.notes <> "Differentiated from "Artocarpus" lessigiana in that multiple major veins feed each lobe. Given that none of these veins are >75% of the gauge of the midvein, I am calling them all secondary veins. This then leads to having agrophics (minor secondary veins) near each lobe apex."," ^

Perhaps I got this error due to using > or % in my note?

**Comment by ecurrano** [comment]
When I tried again but removed >, I got this error message: Error: Invalid input '(': expected whitespace, comment, result fields of a procedure, USE GRAPH, LOAD CSV, START, MATCH, UNWIND, MERGE, CREATE UNIQUE, CREATE, SET, DELETE, REMOVE, FOREACH, WITH, CALL, RETURN, UNION, ';' or end of input (line 40, column 39 (offset: 1201)) " CALL apoc.do.when (" ^

**Comment by ecurrano** [comment]
No error message when I removed both > and %.

**Comment by ecurrano** [comment]
End ask: Is it possible to allow any special characters in the Notes field in the Description Node?

**Comment by NoisyFlowers** [comment]
It's not the > and %. It's the double quotes within the string.

This is fixed in paleobot/pbot-api@2e7661f4ac376c7dcc623f3d1e97b507e8948fe7

merged to master, deployed to dev and prod (note: dev is having some problems and not responding well at the moment).
