### ISSUE TITLE
Unable to create new image node

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#272]
Error message: Error: Unexpected token '<', "<html> <h"... is not valid JSON

Here's what I attempted to submit- keeping things as simple as possible to try and understand where the glitch was.
![Screen Shot 2024-02-16 at 2 59 59 PM](https://github.com/paleobot/pbot-dev/assets/72828382/ef08d11e-7e7b-4d9a-96f8-29886ab64004)

**Comment by NoisyFlowers** [comment]
Have you been able to create any Image nodes on prod or do they all fail like this?

**Comment by ecurrano** [comment]
Still having this problem on prod. I retried the original problem and then tried out an image of a different specimen in a different collection, too.

**Comment by NoisyFlowers** [comment]
I stopped the api server in pm2 and ran it manually with debug options turned on.

I was able to create an Image node using the data in the above example and a dummy image.

I restarted the api server in pm2.

I was again able to create an Image node.

https://pbot.paleobiodb.org/query/specimen/a4da50ce-0688-4276-9289-fac8dedf9be0?includeImages=true

It's possible there is a problem with the image itself. If you can send it to me, I'll try it with that.

**Comment by NoisyFlowers** [comment]
Investigating the problem over zoom revealed that it likely was an upload size issue. nginx on dev is configured for 15Mb. nginx on prod is not configured so uses the default 1Mb.

I've changed the config on prod. Give it a try and let me know if it works.

Also, I've opened paleobot/pbot-client#34 to address the useless error messaging.
