### ISSUE TITLE
Data to play with for OTU descriptions & synonyms

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#277]
To help us play with merged descriptions and synonyms, I entered some real Bighorn Basin data that is a fun story. We initially had two morphotypes, "JAY" and "Arial", which were in part different morphotypes because we had different features preserved at different sites. As we added sites and specimens, we could see more features and similarities between the two. So, we lumped them into the "JAY Arial" type.

I have entered a selection of specimens belonging to JAY and to Arial, and done a description for each of the original morphotypes based on a composite of specimens. I have also created an OTU that includes all the specimens and thus both descriptions. No holotype chosen.

This dataset will be in both stage/prod and dev. In dev, I will also create both the JAY and the Arial OTU so that we would be ready to try out the synonym function. I'm keeping the data private because it is real and unpublished, but everyone on the PBot core team is a member of the group (as is Scott Wing).

**Comment by aazaff** [comment]
Curious to hear more about this at the next meeting.

**Comment by aazaff** [comment]
A fix for synonym and comment was deployed on dev as part of #295. Please check if it works with your examples as expected.

**Comment by aazaff** [comment]
I am closing this just to merge with #295 for cleanliness...
