### ISSUE TITLE
EarthCube Standards & Specifications

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#28]
We need to remember that EarthCube has a document on [Standards and Specifications for Projects](http://library.ucsd.edu/dc/object/bb7786965d/_1.pdf). We should all read this document and make sure that we are following best practices as much as possible.

GeoCODES was also highlighted during the EarthCube annual meeting.

**Comment by clairecleveland** [comment]
@ecurrano Is this something that Botany Team should start to look at?
