### ISSUE TITLE
PBot Explore: Person Search

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#280]
Here is how we would like the PBot Explore Person Search to look:

**Search parameters**
Surname
Given name
Email
ORCID
PBot ID
Groups

_Note: PBot ID will be a search of Person ID._

**Comment by NoisyFlowers** [comment]
This, as well as a fuzzy-ish search on surname and given, are in
paleobot/pbot-client@825cf5f73da00fb02cf56a9863e7a48db1301541
paleobot/pbot-client@4527fe885fb8b46caa605e9d445585b81bf902f9

Merged to master and running on dev

I can't fully implement a fuzzy text search. Neo4j has that ability, but there is no way to access it via graphql at this time. However, I have implemented a fuzzy-ish search using some regex stuff that our graphql package does provide. I think it feels about right for our needs. Let me know what you think.

**Comment by ecurrano** [comment]
I think this fuzzy search is fine for now, given the time constraints. Great work, Doug!

After some playing, I see that the search is no longer case sensitive (super important) and that it will return all searches with the exact combination of letters you have typed. So, if you type "u", you get everything with a u. If you leave off letters at the beginning or the end, you will get what you were looking for. But, if you have a typo, or are missing a letter in the middle of a name, then you will not get it returned.

We can make it clear in training that this is how the search works. Probably not super important for people, but maybe more important for specimens.

**Comment by ecurrano** [comment]
Looks good in dev, and ready for prod, if not already there. If it is on prod, we can go ahead and close this issue
