### ISSUE TITLE
PBot Explore: Reference Search

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#281]
Here is how we would like the PBot Explore Reference Search to look:

**Search parameters**
Author
Year
Title (fuzzy search preferred; search all title fields if they are different fields, eg Chapter title)
DOI
PBDB ID
Published vs unpublished

_Note: we would like to eliminate having to initially choose a reference type because 1) it's an extra button to push, and 2) people may not know how the reference was entered. It can be tricky to figure out whether a monograph is a journal article or standalone book, and these are often inconsistently applied._

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-dev@d24e4dc1f9fb7fafabf706e07272a5cc0456abc3

merged to master and running on dev

**Comment by ecurrano** [comment]
Should we consider getting rid of the Published checkbox? I'm not sure it's especially useful, and I'm also not sure it works the way one might expect. It seems that if you have the box checked, you get both published and unpublished references, whereas if it is unchecked you get only unpublished references.

**Comment by ecurrano** [comment]
@doricon: see previous comment and weigh in. If we want to keep this as is, then you can go ahead and close the issue.

**Comment by doricon** [comment]
I can understand someone wanting an option for "published only", but I would prefer the default to be a list of everything. I am getting "Error :(" when using the search right now in dev.  In the live PBot if I submit a blank search (to see all refs) I get the following error: 

![Screen Shot 2024-09-24 at 10 33 45 AM](https://github.com/user-attachments/assets/9dc44941-eabc-4e3b-83ba-36787289f11b)

**Comment by doricon** [comment]
Note: that error only happens when I have the "published box checked", when it is unchecked I get a full list of unpublished references

I think it is fine to close this once the bug is fixed.
