### ISSUE TITLE
PBot Explore: Collection Search

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#283]
Here is how we would like the PBot Explore Collection Search to look. Note this one is more complicated as there will be accordions, and cross-searches are also required (e.g., we want to be able to search for all collections that contain a given OTU). A star indicates the accordion header, and a dash indicates the searches in that accordion. Anything in brackets indicates where the particular search field exists or additional clarifications and should not be seen by users.

Search by Collection name [fuzzy search]

*Search by Taxonomy
- OTU name [we want to be able to enter an OTU name and get a list of all collections that have a specimen assigned to that OTU]
- Major taxon group [OTU node; get a list of all collections that have, for example, dicots present]
- PBDB parent taxon [OTU node]
- Family [OTU node]
- Genus [OTU node]
- Specific epithet [rename of species; OTU node]

*Search by Fossil Characteristics
- Parts preserved
- Notable features preserved
- Preservation modes

*Search by Time
- Timescale
- Maximum Interval
- Minimum interval
- Ma range [numerical range, if this is possible currently]

*Search by Location
- Latitude & Longitude [separate entry fields for each, fuzzy search- like what PBDB does]
- Country
- State/Province

*Search by Stratigraphy
- Group
- Formation
- Member
- Bed

*Search by Metadata
- Enterer [no idea where this is held]
- Reference
- Groups

**Comment by ecurrano** [comment]
Linking to #279 as it might be complicated to get search by time fields to yield true results.

**Comment by NoisyFlowers** [comment]
Are we sure we don't want to keep search by specimen?

Also, I think we should keep PBot ID (currently Collection ID). Just move it to Search by Metadata

**Comment by ecurrano** [comment]
Yes on PBot ID under Search by Metadata.

Also, yes on the search by specimen- that makes good sense that someone might have a specimen number and want to know all the information about the collection. I am ambivalent about where to put this. Maybe under Collection name and not in a dropdown, as it doesn't really fit into any of the dropdowns? @doricon , @clairecleveland : any thoughts?

**Comment by NoisyFlowers** [comment]
Some of this is in
paleobot/pbot-client@11e357967648d838c4a335437e543200eebc7a80
paleobot/pbot-client@4bb7f8053b0ad73e0dcd594a4e485e2996b72f74

merged to master and running on dev.

Complex queries are stubbed. I've retained some things I thought could be valuable.

**Comment by clairecleveland** [comment]
Hello Ellen,

I'm looking at this now. Did you get my email with the PBot Update email?
Should we talk about that today after meeting with Doug and Andrew?

Cheers,
Claire

**Comment by clairecleveland** [comment]
@ecurrano It looks like Doug created a new accordion for specimen. I think this is appropriate and I like its placement above metadata but toward the end of the list. It's still easy to find even on a smaller device.

**Comment by NoisyFlowers** [comment]
Taxonomy search is in 
paleobot/pbot-client@a5b190c3ffd9c591cac8625964212901f752a524
paleobot/pbot-client@a878343b08ee33641dcdc5f49062fe54d923ab50

merged to master and running on dev

**Comment by NoisyFlowers** [comment]
Location (lat/lon) search is in
https://github.com/paleobot/pbot-api/commit/652479b8a184ba3ba1a6b66e56dc413c58c874a8
https://github.com/paleobot/pbot-client/commit/1e362dc9dd9d57d4ac6bb18fbb2d0c4a304ccf71
https://github.com/paleobot/pbot-client/commit/dc09931443d71efcf4a0979c95ff72235679552d

Merged to master and running on dev.

Note 1: To create the required location property in the Collection nodes, this cypher was run before turning this loose:

match (c:Collection  )  
set
    c.location = Point({latitude: c.lat, longitude: c.lon})
return c
Note 2: The api changes were made in a way that should maintain continuity with the previous. In other words, you can access the deprecated lat and lon properties as well as the new location.latitude/location.longitude The lat and lon properties accessed through the api are generated on the fly from those inside location.

Note 3: Ideally, we would also delete the old lat and lon properties in the nodes. I'm leaving them around for now in case there are any latent problems with the conversion cypher in note 1. However, they are no longer accessible through the api (see note 2).

Note: 4: The search radius is currently set to 1500 meters. Let me know if we want it bigger/smaller.

**Comment by NoisyFlowers** [comment]
Lat/lon search radius changed to 10000 meters in
paleobot/pbot-client@5c6a6aea7129c7a3bc434f518c06dcea7a07a75d

merged to master and running on dev

**Comment by ecurrano** [comment]
A township is 6mi x 6mi, and so the 10km radius will allow for placement within a township (if all you have is township/range information). Ellen needs to look into protected fossil locality information to make sure that these would fall within the search.

**Comment by NoisyFlowers** [comment]
Parts Preserved and Notable Features search of member Specimens is in
paleobot/pbot-client@03faa01a8bf7c96696e40b817484774916d15545

merged to master and running on dev.

This completes all the changes described above except numerical time search. We might consider tracking that one on its own issue.

**Comment by ecurrano** [comment]
One thing that kills me every time I haven't worked in PBot for a while is that I forget that I need to choose the correct Group if the data are not in the public sphere. I know we don't have time to implement the search such that PBot automatically searches everything the user has access to. But, I think it would be helpful to move Groups out of the metadata accordion and put it right under "Name". Or alternatively move Metadata to be the top accordion. Whatever is implemented for Collection should also be implemented for OTU and Specimen.

**Comment by clairecleveland** [comment]
If this is added to next version enhancements, we might think about
defaulting to a search filter called “user” that includes everything a user
has access to. Then when necessary, the user can limit the search to a
group such as public or otherwise.

**Comment by ecurrano** [comment]
I like Claire's idea about the "user" option. I do still think it would be useful to move Group out of the metadata accordion and under name, not in any accordion. Or, it could go under the accordions and above the include specimens checkbox.

**Comment by ecurrano** [comment]
#292 relates to this.

**Comment by doricon** [comment]
I left a commend in #292 concurring with moving the group option out of the accordion. We can leave that issue there and close this one.
