### ISSUE TITLE
PBot Explore: Person Search Results

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#284]
We like the current search results format, but wonder if it is possible to add whether the person is a registered user or not.

**Comment by NoisyFlowers** [comment]
This is in
paleobot/pbot-client@4527fe885fb8b46caa605e9d445585b81bf902f9

Merged to master and running on dev

**Comment by ecurrano** [comment]
Looks good. After our meeting 5/22 we should close this issue.

**Comment by ecurrano** [comment]
Issue ready to be closed if on prod.
