### ISSUE TITLE
PBot Explore: References Search Results

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#285]
For the initial Query Results, we would like to see Year. Title. Currently it is only title.

For the Full Reference Display Results, we would like to see:
Publication Type
Authors
Year
Title
DOI
PBot ID
PBDB ID
and then run down everything that could be filled in, in the order of the entry form.

**Comment by NoisyFlowers** [comment]
Some of this is in 
paleobot/pbot-dev@afd771b098fc492d98ee497cd0b18179001af890

merged to master and running on dev

I'm maintaining the headings layout and the Identity section pending discussion. This is for consistency with the Collections output, which, per #287, will maintain the same.

**Comment by ecurrano** [comment]
I love the initial query results. So easy to find things when year is first and the sort term.

Given that we have year and title on the quick results page, I think that the most useful thing would be to have the authors listed first, as that is the most logical check of whether you have the correct reference. 

I find it a little confusing to have Identity separated from Publication Details, as it's not intuitive to me at least what makes an "Identity." However, I don't have particularly strong feelings. We're not a reference management system and Doug's time is needed elsewhere.

**Comment by ecurrano** [comment]
Not worth Doug's time to make any additional changes here. Ready to close once on prod.
