### ISSUE TITLE
PBot Explore: Specimen Search

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#288]
Here is how we would like the PBot Explore Specimen Search to look. Note this one is more complicated as there will be accordions, and cross-searches are also required (e.g., we want to be able to search for all specimens assigned to an OTU). A star indicates the accordion header, and a dash indicates the searches in that accordion. Anything in brackets indicates where the particular search field exists or additional clarifications and should not be seen by users.

Search by Specimen Name [fuzzy search]

*Search by Taxonomy
- OTU name [identified as]
- Major taxon group [OTU node]
- PBDB parent taxon [OTU node]
- Family [OTU node]
- Genus [OTU node]
- Specific epithet [rename of species; OTU node]

*Search by Fossil Characteristics
- Parts preserved
- Notable features preserved

*Search by Time
- Timescale
-- Maximum Interval [Collection]
-- Minimum interval [Collection]
- Ma range [numerical range, if this is possible currently; Collection node]

*Search by Location
- Latitude & Longitude [Collection node; separate entry fields for each, fuzzy search- like what PBDB does]
- Country  [Collection]
-- State/Province  [Collection]

*Search by Stratigraphy
- Group  [Collection]
- Formation  [Collection]
- Member  [Collection]
- Bed  [Collection]

*Search by Metadata
- Collection name  [Collection]
- Enterer [no idea where this is held]
- Reference
- Groups

**Comment by NoisyFlowers** [comment]
Some of this is in
paleobot/pbot-client@11e357967648d838c4a335437e543200eebc7a80
paleobot/pbot-client@4bb7f8053b0ad73e0dcd594a4e485e2996b72f74

merged to master and running on dev.

Complex queries are stubbed. I've retained some things I thought could be valuable.

**Comment by clairecleveland** [comment]
Question: @ecurrano @doricon 

In OTU, you can search by characters and states using "Search by description"
In Specimen, you can search characters and states using "Schema"

For consistency, do we want the words "Search by" included. Also, do we prefer searching by "description", "schema", or "character states"? Currently, you can only process a search if you go down to the state level.

**Comment by NoisyFlowers** [comment]
Taxonomy search is in 
paleobot/pbot-client@05c1f5929348eecac80ef0c8d6e3794f0f2c2b48

Time (interval) search is in 
paleobot/pbot-client@650fb4d8e9814220e145ec68dfecaf015be8524a

Location search is in
paleobot/pbot-client@e6ccac997a09072a5777805b3eab89025e8cf3c8
paleobot/pbot-client@b975186331b5d588ed43c9556d6686c164557d4f
paleobot/pbot-client@f5479c2975d6881a2ce4a0d70c34ee243f84561a

Stratigraphic search is in
paleobot/pbot-client@07510e5664023df098363a47c2bc858628b5d3da

Enterer search is in
paleobot/pbot-client@508590c9d78b76f4205c04f9cfdada1eb9911e03


This should cover all the changes described.

**Comment by clairecleveland** [comment]
Fantastic! Excited to look at these.

**Comment by doricon** [comment]
Woo hoo! Excited to see it!

Glad to have you back Doug and hope you are feeling better!



Dori L. Contreras, Ph.D.

Curator of Paleobotany
Perot Museum of Nature and Science

E  ***@***.******@***.***>

P  214.756.5783



[pastedGraphic_1.png]<http://www.perotmuseum.org/>



2201 N. Field Street, Dallas, TX 75201  |  perotmuseum.org

[pastedGraphic_2.png]<https://www.facebook.com/PerotMuseum/>

[pastedGraphic_3.png]<https://twitter.com/PerotMuseum>

[pastedGraphic_4.png]<https://www.instagram.com/perotmuseum/>





________________________________

**Comment by ecurrano** [comment]
I have some nit-picky comments about the order of fields and adding or removing search fields, but not sure if it's worth anyone's time to go into this now.

**Comment by doricon** [comment]
@ecurrano do you want to write them down here, at minimum for the record?
