### ISSUE TITLE
Comment doesn't work

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#295]
Get the Error :( when selecting synonyms. We thought this might be related to public vs. private, but some testing indicated an actual code issue.

**Comment by NoisyFlowers** [comment]
This problem originates from our hacked code in paleobot/neo4j-graphql-js.

There is a fix for this in 
paleobot/neo4j-graphql-js@d847cab096ab77f50148531720904f73e52e3d5e
paleobot/neo4j-graphql-js@cc7f9ea40939b0cc7c8c06974461ec53de3e6528

I am keeping this on the ddm-dev branch for now until we see if there are any side effects. It is running on dev via a temporary mod to package.json.

**Comment by doricon** [comment]
I made a new synonym and then tried to comment on it. After pressing submit I received the following error message as the Results: 
Error: Variable `n` not defined (line 1, column 9 (offset: 8)) " RETURN n" ^

I also used the search function for the taxon I proposed a synonymy for (and clicked include synonymies), but the results page does not yet show the synonymy.

**Comment by aazaff** [comment]
So it sounds like there was a problem with creating the initial synonym rather than with the comment.

Just for Doug's convenience. I believe the OTU's she is mentioning are "JAY" and "Arial" if you want to look at the logs.

**Comment by doricon** [comment]
Interesting, I can find the synonymy that I made when I go to make a comment, or when I choose to 'edit' a synonymy. I made the one between Platanites raynoldsii and "Eatibus" anythingus

**Comment by NoisyFlowers** [comment]
Regarding all the June 4 comments: what machine were you trying this on? The fix was only running on dev at that time.

It has since been merge to master in paleobot/neo4j-graphql-js and is running on both dev and prod(stage)

**Comment by doricon** [comment]
I was probably trying it on dev. However I just tried on prod, after making a synonym for "Jose Creek dicot DT26" and "Hack-A-Thon OTU 230808.CC.1". 

I was able to make the synonym. But I could not add a comment to it - when I tried to submit the comment it gave this error:
Error: Variable `n` not defined (line 1, column 9 (offset: 8)) " RETURN n" ^

**Comment by NoisyFlowers** [comment]
The "n" issue was a separate problem from the original. This one was due to improperly generated cypher code in the isDuplicate routine of Resolvers.js.

This is fixed in 
paleobot/pbot-api@44179fc45b7fd74ce978d218d8780b08fd47b5c5

currently on ddm-dev branch and running nowhere
