### ISSUE TITLE
compatibility from MyFossil EMuseum and QC workflow for admitting specimens

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#30]
The below comment came from the workshop survey. I only briefly looked at the EMuseum site, we should check it out further. 

PBot connection to other sources:
"I'm assuming it will be able to take voucher specimens from the MyFossil EMuseum since it is linked through GBIF and iDigBio? MyFossil Emuseum workflow might be something to model for admitting specimens for quality control."

**Comment by clairecleveland** [comment]
Ellen, Dori, and Rebecca, should we add this to our agenda say in late May after Ellen's lab gets settled after the move?

**Comment by aazaff** [comment]
I have no idea what any of this means? Can we presumably shelve it since it was not in our proposal? @ecurrano @doricon @clairecleveland

**Comment by doricon** [comment]
Yes, we should shelve it. This was a good reminder to me though to check out that resource that was mentioned! Looks like we could consider it for an image repository for specimens.... maybe.
