### ISSUE TITLE
issue editing collections

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#303]
I am trying to edit the name of a collection in prod. This occurred specifically for 43b91f6e-51bf-4bc4-9709-c2e9ec017e25, but also seems to be true for others.

When I attempt to submit the edit, I get the following error message: Error: Collection mutation must have either location or lat/lon

The collection does have a lat/long.

**Comment by NoisyFlowers** [comment]
This is already tracked by paleobot/pbot-api#44
