### ISSUE TITLE
Add schema property to Description nodes

### ISSUE THREAD

**Issue by NoisyFlowers** [paleobot/pbot-dev#31]
Right now, the only way to find out what Schema a description complex uses is through the Character nodes. It would facilitate graph navigation to add a property to Description nodes for this. To be clear: I mean a relationship between Description nodes and Schema nodes (working with graphql has me thinking in terms of properties).

**Comment by aazaff** [comment]
I have no opinion on this and defer to your judgment.

**Comment by aazaff** [comment]
I'm pretty sure we did implement something for this, but @NoisyFlowers will close this when confirmed.

**Comment by NoisyFlowers** [comment]
This is now handled by the APPLICATION_OF relationship between Description and Schema nodes
