### ISSUE TITLE
Macrostrat API calls are hitting V1 instead of V2

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#312]
This is completely my fault for giving @NoisyFlowers the wrong link. The Macrostrat API has been on v2 for 8 years or so already but I must have accidentally said to use V1. The Macrostrat team noticed our calls to v1 in their logs and have asked us to change it when we have a chance.

https://macrostrat.org/api/v1/defs/lithologies
https://macrostrat.org/api/v2/defs/lithologies

You can quickly check https://macrostrat.org/api/v2/changes for a list of the relevant info... I've snapshotted the relevant one

/defs/lithologies
input and output parameter id is now lith_id
Multiple input lith_id now accepted
Removed lith prefix from all fields except lith_id

Interestingly... I did a search of our codebase and did not find any actual instances in our API code of us hitting macrostrat at all? Possibly this is because the relevant schema files are on the git ignore file?

**Comment by NoisyFlowers** [comment]
This is fixed in 
paleobot/pbot-client@55e3ca7c0e2589b5742a024e500b3a3399cf18f4

On master, but I can't deploy to dev/stage because I am no longer able to RD to those machines.
