### ISSUE TITLE
specimen info not properly displayed when enter from OTU

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#322]
If I search for specimen, everything seems to populate correctly on the results page (image - although note broken now, taxonomy, description, etc.). Here is an example of the direct link. http://128.196.12.150/query/specimen/6bd90def-2739-4661-9cf3-da38ac0f9448?includeImages=true&includeDescriptions=true&includeOTUs=true

But, if I instead start at the OTU results page and then click on a link for a specimen under additional specimens, the image, taxonomic data, and description does not carry over. The screenshot below is for the same specimen. And here is the direct link I get for that page: http://128.196.12.150/query/specimen/6bd90def-2739-4661-9cf3-da38ac0f9448
 
<img width="987" alt="Screen Shot 2024-11-14 at 2 17 48 PM" src="https://github.com/user-attachments/assets/279aa395-781e-46b2-92af-2c9e28651dbc">

**Comment by ecurrano** [comment]
Users should get to see all linked information no matter how they enter the specimen results page.

**Comment by ecurrano** [comment]
This is especially important since I think this is the only way to view descriptions of additional (not type or exemplar) specimens

**Comment by NoisyFlowers** [comment]
This is in 
paleobot/pbot-client@a3152dc3d4af7860f753916dfb87d5e9b23a1536

On master, not running on dev or stage
