### ISSUE TITLE
Synonym policies and implementation

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#323]
If you realize that two OTUs are the same and then create a synonym relationship between them, what happens next, beyond of course that you can now view the synonym on the OTU results page? Currently, nothing, correct? The specimens stay under the original OTU, as do the associated descriptions and images. So, it is on the user to decide which name has priority and reassign all the specimens to that OTU? And make updates to which specimens are exemplars such that the range of characters would be captured in the merged OTU description? We should talk through how to do this and whether there are functions that could be implemented in PBot to make this easier.

**Comment by aazaff** [comment]
I am closing this. There's is no way we can do anything about it now. It will have to be rolled into the PBDB 2.0 upgrades.
