### ISSUE TITLE
Support for auto-calculating parameters based on pre-defined functions.

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#34]
(original email)
> I have a request from the quantitative group. There are only so many raw values that the quantitative dicots users enter, but there are also calculated values. The calculated values can be tied to the specimen as raw value data is entered. In cases where not all values required for the formula are available, could PBot could return NA or Incomplete or something like that? They don’t want 0s or incomplete calculations returned if not all the required data is available. I’ve asked the group to provide names for the calculated values, formulas, units, and written definitions. Anything else they need to supply?

As I understand this question, what is being asked is (**as an artificial simplified example**) IF users provided a `Length` measurement and a `Width` measurement, could PBot: 1) autocalculate an `Area` and 2) if length and/or width is missing would `Area` return NA. The second part of this is trivial, everything that doesn't exist is already NA in the graph database (there's no node at all).

As for part 1 (auto-calculation), I see huge problems with this. To do this in a way that wasn't a completely hard-coded hack, we would need to essentially make an 'equation builder' tool as part our schema definition forms. That's WAY out of scope.

**Comment by ecurrano** [comment]
Based on Andrew's response, I think we would want to follow the PBDB model for this, in which someone writes code (or R-package) that can be downloaded from our website to do the calculations. So, on PBot we store any values you can measure, and then there is a script to work with the PBot output to do the calculations. Once we know what the output will look like, perhaps the quantitative team would be willing to work on that code? Do we need input from the quantitative team on what the output would need to look like to be able to write the code?

**Comment by clairecleveland** [comment]
Hello,

Andrew, great point. I had not thought of that aspect of developing the
schemas. Ellen great solution! I'm on it.

One thing I think we should not advertise yet, but think internally about
how it could work in the future... Folks might think up coding aspects of
PBot that we did not, and that would be valuable to the community. Under
thoughtfully constrained circumstances, how can we allow users to propose
for funding specifically to pay developers to create new "plug in" coding
for PBot? E. G. If I had a complicated but widely used set of traits that
required schema development beyond what PBot offered, could I pay a
developer to write the code for the schema and have the schema uploaded to
PBot? Eventually, NSF and other funding sources are going to have to
support funds for scientists to outsource non-science expertise so they can
focus on science itself. When managing large datasets, this is no less
valuable than sending samples to an expert lab for analysis.

I'll talk to the quantitative group about the calculations.
Claire
