### ISSUE TITLE
Support for user groups

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#36]
We've already spec'd this out in detail, but in short there will be a User Group node class (specific name TBD). All other nodes will be attached to at least one User Group.

Of special note is the `Public` user group, which has some special characteristics: 1) once made public cannot be made unpublic; 2) once made public cannot be deleted from database (only soft deleted); 3) version history is reset upon being made public. See #33 and #32

**Comment by NoisyFlowers** [comment]
Notes from today's refresher:

Role node types determine overall api access privileges (admin/user/etc.)

Group node types determine viewing (read) privileges. Used for ad hoc grouping of users and data. 
	User nodes and all other node types can attach to Group nodes.
	A user can only see things that are attached to groups the user is also attached to.
	Public
		All users will be members of Public (attached to Group node called Public)
		A user in the Public group can see things that are also in Public group
		When a non-User node is attached to Public, it gets detached from all other groups 
			This is part of a cleanup on version history when going public.
			Editing rules are different for Public
				
	Andrew's Team (nonpublic group example)
		Any user attached to this group can see any data nodes also attached to this group
		
	Users and other node types can belong to multiple groups. Non-User nodes that are attached to Public can be attached to no other Group nodes 
	
How to create a group?
How to assign users to group?

**Comment by NoisyFlowers** [comment]
Basic Group node maintenance is in pbot-api commit 65d753bec768240174840ff75fb1f320cc8c7e10 and pbot-client commit 63fabcdf43db3bcae83f8d4ad138389df1bf8a28.

Note: Testing the api uncovered a serious bug in use of Cypher UNWINDs throughout the graphql schema that needs to be addressed. This is covered in pbot-api issue [https://github.com/paleobot/pbot-api/issues/10#issue-1111115967](url)

**Comment by NoisyFlowers** [comment]
There's been a lot going on with this. 

api commits db19f445d142b5459e35e3b6bb0426854fb3318d through 9f5201551693e71e0027e960439a7781354d3eeb. 

client commits 577de12df60bfc6912630c33583763d55251a025 through 89af270680e259015fde0455137295334dcf835c

Also forked neo4j-graphql-js (https://github.com/paleobot/neo4j-graphql-js) in order to inject group check on every query.

**Comment by aazaff** [comment]
More or less done in a big-picture sense. Open separate issues for any more specific bugs in the future.
