### ISSUE TITLE
Ways to track primary vs. secondary etc. traits

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#38]
Similar to how we track authorship order, we may want to capture in some or all entries the "order" of precedence for states of a character.

**Comment by ecurrano** [comment]
Possibly on a related note, it is important to capture the frequency of occurrences of character states. This is important both for descriptions of individual specimens (e.g., tertiary veins predominantly straight opposite percurrent and occasionally sinuous opposite percurrent) and for OTUs (most specimens are pinnate, but some are palmate). To some extent, it will be up to the community how to specify trait distributions (rare vs common, or actual numerical estimations). But we might want to discuss whether this will be entirely entered by the users- and thus we need to create the forum to do so- or whether at least in the case of the OTU description, it can be done algorithmically.

**Comment by aazaff** [comment]
This is related to #56, but is more complicated because there is the intermediate CharacterInstance involved. Basically we just need to add the "priority" property on the relationship.

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-api@04c185d30762b26c432e369c5a49ddc91fc7c5c4 and paleobot/pbot-client@4d792540939b95a9e2e9e18412aeb4535c0f8f29
