### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#42]
The Paleobotanists are starting to think through how the output of a database search will work. We were thinking about an Etsy model, when you click on an item and it opens in a new window. This allows the user to quickly click between many OTUs or have multiple OTUs open at the same time without requiring the web interface to be programmed to allow this.

**Comment by clairecleveland** [comment]
I really like this idea Ellen. I think the architecture for searching data/properties/relationships "fields" is something we should be digging into mentally right away so we can all be on the same page. I'd really appreciate a low-key presentation from Andrew and Doug just on the correct terminology for these things. This would be a good agenda item soon so Andrew and Doug can get us understanding how data gets pulled back out and the limits to searches our decisions will impose. This will be incredibly important in determining how we set up our data/properties/relationships "fields" as we design interfaces "forms/views."

**Comment by aazaff** [comment]
This issue is subsumed in various other issues and is now outdated.
