### ISSUE TITLE
More Robust User Registration Checks

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#43]
Right now we just check for matching email, but we should probably have more robust soft-matching checks. Right now both Claire and I have duplicate users in the database because we ended up using different emails when we registered.

**Comment by aazaff** [comment]
@NoisyFlowers 

As an addition to this, should we add support for multiple emails per person node?

Should we separate out account/user tracking to a totally separate node type that get attached to a person node?

**Comment by clairecleveland** [comment]
@aazaff @NoisyFlowers Should this be addressed before we get formal new registered users at HackAThon? That way if they change their mind and try to mess things up after the HackAThon, we don't have to clean it up. Maybe even something like search for similar user names, tell user similar names exist...Are any of these you? Then they can go back and log into their existing account? I was hoping maybe there was "canned" code for something like this, but probably wishful thinking.

**Comment by ecurrano** [comment]
I believe this is done and can be closed?
