### ISSUE TITLE
Eventually we want to have support for a SYNONYM_OF relationship

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#45]
This should be drawable between characters and possibly? states.

**Comment by clairecleveland** [comment]
I know you've talked about this in the background. Could we possible add this to the agenda just so that non-programers can have an understanding of what functionality this provides/limits?

**Comment by aazaff** [comment]
That's fine, let's add it to the google docs agenda for next week, but I'm going to close this as a duplicate of #55
