### ISSUE TITLE
Create a SAFE and CANONICAL create database script

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#46]
We should have a canonical cypher script stored somewhere that recreates the "best" version of the database.

**Comment by NoisyFlowers** [comment]
There are three ways to backup and restore a neo4j db. 

The first is using the backup/restore commands. These allow on-the-fly backup while the db is running. They also allow incremental backup. I'm not sure what format the files are in. These commands are only available with Enterprise. 

The second is using the dump/load commands. These require the db to be shutdown first. The resulting file is a proprietary binary format. 

The third, and the one that best fits our needs, is by calling [apoc.export.cypher.all](https://neo4j.com/labs/apoc/4.4/overview/apoc.export/apoc.export.cypher.all/). This is done on a live db. The output file is readable cypher (well, it's cypher at least, though not particularly readable). For a standard linux install, the files are written to /var/lib/neo4j/import by default. 

The following cypher can be run via cypher-shell or Neo4j Browser:

```
CALL apoc.export.cypher.all("pbot-" + timestamp() + ".cypher", {
    format: "cypher-shell",
    useOptimizations: {type: "UNWIND_BATCH", unwindBatchSize: 20}
})
YIELD file, batches, source, format, nodes, relationships, properties, time, rows, batchSize
RETURN file, batches, source, format, nodes, relationships, properties, time, rows, batchSize;
```

The format and useOptimizations are superfluous here, as cypher-shell and UNWIND_BATCH or the respective defaults.

For slightly more readable output, one can set useOptimizations to NONE. 

I've exported on dev, using the cypher above; copied the file to my local machine; imported into a new db use the following command:

```
cat /home/douglas/pbot-1666306214852.cypher | bin/cypher-shell -u neo4j -p password
```

The resulting db appears to contain everything from dev.
