### ISSUE TITLE
Possible solution for discussing specimen image details

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#47]
For future consideration when linking iDigBio images to specimens and OTU's. During past conversations we have discussed users being able to discuss details about specimen images. This creates problems because we can't annotate images in iDigBio. A possible solution would be to offer a couple (different sizes) of grid overlays so users can specify the location of details on an image. For example, "the insect damage in cell D6" or "the tooth in cell M34."

**Comment by aazaff** [comment]
This is a promising idea. I think we need to sort our more broadly how much image information we will store internally and how it will be stored, but something along these lines sounds reasonable. More research is needed.

**Comment by clairecleveland** [comment]
Yes, definitely needs more thought. It seems like we are heading in the direction that PBot may store a limited set of images for OTUs and one image plate for schemas. The mass of images for specimens etc. would be stored in iDigBio and other image libraries. Is the general direction?
