### ISSUE TITLE
Bulk Uploads

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#49]
Revisiting the question following our discussion with the quantitative traits group. We know that there will be an initial need for uploading legacy data, but then there is also the possibility that going forward, there may still be a need to for a bulk uploader. Possible cases:
1. People working in places without stable internet who would need to record data offline and then bulk upload.
2. A lot of numerical data is generated at the same time (e.g. quantitative traits group). We don't want people to have to retype all those numbers.

**Comment by aazaff** [comment]
Yes, I concur with Claire. Bulk upload according to some pbot standard would be different from supporting legacy upload. I think we definitely know we need the former. The latter it sounds like is more questionable? It could be argued that in a Community Curated Database it should be on the users to convert their legacy data to whatever our general upload format would be.

**Comment by ecurrano** [comment]
Batch uploading came up a lot at the Hack-a-Thon!

**Comment by doricon** [comment]
Comments from participants: 

I know that batch entering for specimens is not something that PBOT will do and that it can be done by someone else, but I see it as a huge barrier to using PBOT. Can PBOT task someone talented in R to make this feature and provide a CSV template for batch uploading? I see people getting frustrated with the amount of time it takes to enter in every specimen, considering it could be in the thousands. (GSM)

- I agree with this completely. Not being able to batch upload will result in some gaps in data, a lot of holotype specimens, but few or none of the supporting or additional specimens. Having at least some pre-prepared coding or script or a R widget designed for this purpose? Making it easier to enter large amounts of data will definitely support usability for some users. (Christopher) (Matt) (Agree, Paige)

- Or if its too individual project specific maybe make some examples of what it would look like or hold a tutorial session to teach some of us how to set up our own? (Matt)

**Comment by aazaff** [comment]
I don't know how Matt is progressing, but I think we are agreed that this is now up to quant team and others.
