### ISSUE TITLE
Addition of an OCCURRENCE node also?

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#51]
Hypothetical scenario:

Let's say you go collecting and you notice that there are some snail species mixed in with your collection of plants. You might want to make a note that those species are present in that collection (i.e., in paleobiology database parlance, an occurrence). However, since snails are not plants you are not going to be doing any descriptions or specimen analysis of them, so creating a "specimen" node for them might not be appropriate? One solution would be offer an occurrence node to just track other non-cryptic taxa found with your cryptic fossils.

**Comment by clairecleveland** [comment]
To make sure I understand, these would port to PBDB occurrence nodes but user would just id to most specific level they can such as Gastropoda? If that's the case, I definitely support this idea.

**Comment by aazaff** [comment]
Yes, that's exactly the idea. I also think it makes sense. Leaving this open for the others to vote on though.

**Comment by aazaff** [comment]
The need for this is more or less (not perfectly) obviated by the implementation of "Identified Specimens" category in OTUs. See #90
