### ISSUE TITLE
Vocabulary and Property Attribution relative to Paleobiology Database

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#52]
We list various properties we might track as part of the new COLLECTIONS node in #50.

Some of these properties have controlled vocabularies. For example, entries in the field EARLY INTERVAL and LATE INTERVAL should come from here https://paleobiodb.org/data1.2/intervals/list_doc.html

How will we build this validation into our workflow? As part of the database? the API? the  client? Some mix?

**Comment by aazaff** [comment]
I fixed the link above: should have been https://paleobiodb.org/data1.2/intervals/list_doc.html

**Comment by aazaff** [comment]
Duplicate with #50

**Comment by aazaff** [comment]
Our current assessment is that this would not be a huge deal because it fits the profile of what GraphQL is for.

We would essentially have a resolver that turns our GraphQL query into a query to the PBDB (or whatever external) API.

**Comment by aazaff** [comment]
This is essentially subsumed into #71

**Comment by ecurrano** [comment]
I reopened this because it the minimum and maximum interval fields in the Collection Node need work still. 

Enhancement–Andrew and Doug to discuss, try for HackAThon but NO guarantees. Perhaps pick the timescale and then select only from those intervals. Indents might also help reading the list.

**Comment by ecurrano** [comment]
I know we finished this one!
