### ISSUE TITLE
Image Handling Notes

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#53]
Create a plate for the exemplar OTUs and PBot determines basic template for "plate-like" set up but it's really a collection of a few images that we call dynamic plates. Then each image within the "plate" can be described, include specimen ID and be opened in large view for high resolution viewing. Provide entry field for what each image is showing, ex. teeth. Develop best practices for digitizing plant fossils. The concern is that making plates can be a barrier in time and expense for software. Also, this is updatable for adding new characters as they are found.

**Comment by clairecleveland** [comment]
We'd like to be able to open the plate from within the interface (form view of an OTU) as a separate window (or tab as individuals web browsers allow). This would allow folks to look at the plate of the OTU in one window/tab and compare it side-by-side with a specimen for example.

**Comment by aazaff** [comment]
The new system for images is as follows.

1. New type of node - Images - ONLY attaches to specimen nodes -> image_of relationship
2. Properties
     3. Link - Link either ot external website OR our internal WAF
     4. Citation - free text credits info - e.g., picture taken by Ansel Adams
     5. Caption - free text caption
     6.  Type... tbd, list of additonal tags such as "Really Good Looking" view angles etc.

**Comment by clairecleveland** [comment]
Resolution per Sr. Staff Mtg 2022

Image “tagging” and some rules
o	A. Image plates can only contain one specimen
o	B. Image node property “Caption”
	Text field
o	C. Image node property “Image Display Priority” terms for OTU page
	High—holotype suggested
	Medium—paratypes and exemplary details
	Low—all other images
o	D. Images in carousel
	Ordering would occur for ex. “top 10 images” that are provided in carousel
	Carousel contains button to see additional images
	Specimen ID is provided with the image in the carousel

See comment above: change Citation to Image credit

**Comment by aazaff** [comment]
Bumping this to pbot team... it was stated in the google doc #89 that we needed the "type" property added to images form. What are the list of accepted types?

**Comment by aazaff** [comment]
Superseded by newer image stuff
