### ISSUE TITLE
Implement schema forking and synonymies

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#55]
The concept of subschemas has been raised - i.e., subsets of larger schemas.

1. Is this necessary?
2. How would it be implemented?

**Comment by doricon** [comment]
For question 1: I am not sure this is necessary - currently there is grouping info in the schemas correct? Like the vein characters form a character group within the MLA. I guess the question is whether those groupings within schemas, as currently implemented, can be called out and used without having to worry about the rest of the schema - is that what was desired?

**Comment by aazaff** [comment]
Yes, I think I named it subschema (which is not necessary), but what I really meant was forked schema -- which is something we've all supported in the past and is something that was part of the original spec.

**Comment by aazaff** [comment]
The core of this is redundant with #58 and #59
