### ISSUE TITLE
Administrators Group

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#62]
We need there to be an Administrators Group that allows system administrators to see private data.

Among other things, this allow PBot ExCom to see what data have been in the private sphere for a long time and needs to go public.

**Comment by aazaff** [comment]
Changed this to low-priority because it either already exists or is trivial to add.

**Comment by aazaff** [comment]
I think this already exists, but regardless should folded into the broader groups/upgrade in issue #94
