### ISSUE TITLE
Schema character groups

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#67]
This request comes from Ellen, Dori, and Claire during PBot Botany meeting. Would it be possible to provide a way to group Characters within a single schema? For example group all teeth traits or vein traits together in the MLA schemas. There are numerous schemas that will likely benefit from this and it will help facilitate data entry for users.

**Comment by aazaff** [comment]
I believe we discussed this at length in the past, but I no longer remember where we landed on it. We will have to look in our notes and see whatever we decided before. If we already put the provisions for it in (I think we did actually) then that's fine, if not, then I think it might be too late.

**Comment by clairecleveland** [comment]
issue resolved with new ordering system implemented for characters and states
