### ISSUE TITLE
First keystroke not recorded when using Query/Workbench

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#68]
When using Query/Workbench in current version of PBot, periodically the first keystroke is not recorded after starting a new query or workbench entry. This appears to only happen if you use the same function two times or more in a row. For example, If you query schema then immediately come back to query a second schema OR if you submit a state and then immediately go to enter another state.

Doug is aware of this issue and it may clear up in the updated version. Just didn't want to forget exactly when it was happening in case it needs more work. Likely to be resolved after new version is running.

**Comment by aazaff** [comment]
@clairecleveland Was this fixed?
