### ISSUE TITLE
How to handle hierarchy of characters and states

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#7]
My dummy database currently keeps track of Characters and States.

There are a number of other levels of organization in the manual of leaf architecture such as 'character types' and 'subtypes'. One of the strengths of a graph database is flexibility in developing hierarchies like this. However, we will want to come up with some common conventions for the sake of the user interface.

Example of states vs. substates can be found in the following commit https://github.com/paleobot/pbot_client/commit/4e4c83221ed2987bc69c6fefd2b5f06e8d537349#r47156376

**Comment by NoisyFlowers** [comment]
Regarding states/substates, my inclination is to keep the hierarchy intact and add substrate nodes. 

So, the heirarchy would be:

Reference nodes have 1..n Characters
Character nodes have 1..n States
State nodes have 0..n Substates

Would this create problems when we import (parsing flattened input data)? Would users be amenable to a two-level selection?

**Comment by aazaff** [comment]
I think, if anything users would, in principal, prefer a 2 level solution. I’m worried about the data entry forms becoming too clunky though?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NoisyFlowers** [comment]
If we found that to be the case, we could always flatten them in the form. I like the idea of the graph schema reflecting the hierarchy. 

Do you see any potential problems in the type of queries we might want to run? My gut feeling is that keeping the graph schema honest enables more flexible querying.

**Comment by aazaff** [comment]
I agree that we should keep the database as normalized as possible and we can flatten via the form.

**Comment by aazaff** [comment]
We have this under control now, but I want to leave this issue open because we should probably make some diagrams/documentation to show where we are at with this.
