### ISSUE TITLE
Dropdown/Autocorrect--discuss once new version rolls out

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#70]
Currently dropdown/autocorrect functions working off user history. This means that odd options appear in dropdown menus--may not be desirable to users, will need more testing. Autocorrect functions may force numerous unnecessary keystrokes since scientific language often defies autocorrect libraries, will need more testing.

**Comment by aazaff** [comment]
This is related to https://github.com/paleobot/pbot-client/issues/5. We should handle them together. For now I'm marking this as low priority.

**Comment by aazaff** [comment]
I think this is superseded by all the magnifying glass lookup and other modifications we have underway elsewhere. Closing this.
