### ISSUE TITLE
Add a "provisional" tag to references

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#72]
A way for users to distinguish between a "real" peer-reviewed reference and just a placeholder reference that they had to put in to fulfill our rules.

**Comment by ecurrano** [comment]
To meet PBDB criteria, we will have a field called "reference type", with the options: journal article, book, book chapter, book/book chapter, serial monograph, compendium, Ph.D. thesis, M.S. thesis, abstract, guidebook, news article, unpublished, instcoll

I have no idea what instcoll is and need to ask Mark.

**Comment by aazaff** [comment]
Superseded by our new references workflow in #99
