### ISSUE TITLE
Make definition optional for states form.

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#76]
Do not require a definition for states (as per field lists). We have to enter TBD right now for everything and then go back and delete that individually later which is time consuming. If this could be done soon (if it's not a difficult fix) that would be helpful.

**Comment by clairecleveland** [comment]
@aazaff @ecurrano Update: as of 230607 States still require definitions. Please change so that definition is not required (which Doug will see when rechecks Schemas/Characters/States agains the forms docs). 

We will need to follow up to remove all of the TBD's from states that were entered previously that did not have definitions, but I Matt and I had to enter something.

**Comment by NoisyFlowers** [comment]
This is in paleobot/pbot-client@e28c5d55c66d0158a164485d300744913fd3b357
