### ISSUE TITLE
V 1 Confirmation of creation is time consuming

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#78]
After submitting characters and states we are taken to a screen that shows the long id number and “created”. Can we skip that process somehow? It’s a lot of wasted clicks and time. I think we can "trust" this aspect as this point.

**Comment by aazaff** [comment]
Fixed in https://github.com/paleobot/pbot-client/commit/496c30eca6bc45a550bed6d5ce4d84ac3235050c
