### ISSUE TITLE
Change all long-form fields to the new long-form system.

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#79]
Description field should be bigger and allow scrolling so user does not have to use arrow to move cursor all the way to end of line to correct a mistake.

**Comment by aazaff** [comment]
We now have the new method for long-form text boxes. Need to make sure that is now applied throughout all forms/fields where that is appropriate

**Comment by clairecleveland** [comment]
The long form text boxes in Schema, Character, and State have not been updated yet. Please update long form text boxes as follows:

Schema
- Title
- Purpose 
- Acknowledgements

Character
- Definition

State
- Definition

**Comment by aazaff** [comment]
Is this still unresolved? @clairecleveland

**Comment by ecurrano** [comment]
I didn't realize this issue existed and made new issue #270 . So far, those are the only ones I've come across.

**Comment by aazaff** [comment]
Okay we will close this one and keep the more recent one open.
