### ISSUE TITLE
Numerical sort order--likely impacts all nodes with sort order functions

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#80]
Matt couldn't get the sort order to work for characters after he entered more than 9 under the same "super character." See MLA schema character "Blade Features" which has 16 characters related to it. I think it's simply sorting the number as a string instead of an integer. 

We would like it to sort
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16

Right now it is sorting like this
1,10,11,12,13,14,15,16,2,3,4,5,6,7,8,9

**Comment by clairecleveland** [comment]
@aazaff @ecurrano Update: as of 230606 ordering still needs to be addressed

**Comment by NoisyFlowers** [comment]
This is in
paleobot/pbot-client@e44bddb235afdfa82702b2708ca51ea4d96b892c
paleobot/pbot-client@2e9bbc19efbd63df91285619552b4dcbe7bcbec7
paleobot/pbot-client@654338b3785268a73ee7f79cee4bc77ceca42baa
paleobot/pbot-client@912b987399abca82e08f6caddca10a156c44df95
paleobot/pbot-client@7cd7462ef0c6bac7ed362bf63b59994513b3adc7
paleobot/pbot-client@2d627905b730b499aefc59acfc845aac4b1db048
