### ISSUE TITLE
Move workbench and explore buttons out of the hamburger menu.

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#82]
We often have to bounce back and forth between explore and workbench while entering data. Ideally, just add explore to the workbench screen and workbench to the explore screen (if that's not too difficult).

**Comment by aazaff** [comment]
This was listed in the google doc feedback #89 as well. I agree with taking workbench/ items out of the hamburger, but am classifying this as a low-priority enhancement.

**Comment by aazaff** [comment]
I think that we moved away from this feedback given the many improvements to the interface that have happened since then. Do we still desire this change? @doricon @clairecleveland @ecurrano

**Comment by doricon** [comment]
I'm not stressing about this right now. I'd vote we can keep how it is and revisit if it comes up in the user feedback during beta testing.
