### ISSUE TITLE
Implement error messaging for when users input illegal special characters

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#86]
Certain characters like quotation marks can’t be used in state descriptions (or probably anywhere else).  I don’t know if there’s a way that they can be enabled, or at least have the error message that explains certain character types not allowed.

As a side note, quotations may be included in some reference titles as well.

**Comment by aazaff** [comment]
I think some sort of error message to explain the special characters limitation is probably safest rather than allowing special characters.

**Comment by aazaff** [comment]
@clairecleveland You are the most familiar with this. Was this already added?

**Comment by clairecleveland** [comment]
@aazaff @ecurrano Update: appears this has been fixed. I was able to add " ", °, ö. These symbols were accepted when hit submit and showed up in reports. Yay!
