### ISSUE TITLE
Search specimens/OTUs based on characterinstances

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#90]
1. We need a new route in the query list (?) or maybe just goes under existing Specimen/OTU
2. Need to be able to select a schema, which will then give options for valid characters and states
3. Need to perform a SELECT on OTUs and/or Specimens that have characterInstances of selected characters and states from step 2.

**Comment by NoisyFlowers** [comment]
As described, the user will be able to search for Specimens/OTUs by State (there would be a Character select, but it really only serves to get the right States for the State select. Once the user selects a State, we can run with just that pbotID). 

Do we also want them to be able to search by Character alone?

**Comment by NoisyFlowers** [comment]
For now, I'm implementing a solution that allows the user to search by Schema, or Character, or State.

**Comment by NoisyFlowers** [comment]
OTUs do not have their own Descriptions. We can grab either the Description of the holotype Specimen, or a merged Description of all example Specimens. 

We have to decide whether we want to limit the search to one or the other internally or present the option to the user (via radio button or checkbox).

**Comment by aazaff** [comment]
We are going to clarify the Specimens section of the OTU form with three new types of specimens

1. Identified Specimens: Literally any specimen that someone claims to be this OTU
2. Type Specimens: The set of specimens used to DEFINE the OTU (a subset of identified specimens)
3. Holotype Specimen: The singular BEST specimen (a subset of Type specimens)

When it comes time to search for OTUs, we will define that search based on the merged description of all specimens in the TYPE SPECIMENS category.

**Comment by NoisyFlowers** [comment]
Searching Specimens/OTUs on CharacterInstances (Schema/Character/State) is in:
paleobot/pbot-client@d9b5d0849069f2b293af2a6257be506cf91afe95, 
paleobot/pbot-client@6f349034359cc9d3d3fc9e5736689cdfc9d2188b 
paleobot/pbot-client@750fb7f770ee7e46dcd7c2169b7cd291b4881a14 
paleobot/pbot-client@c8a91692dc06c3f11a8e050a9f57318e7e784fae
paleobot/pbot-client@3b734be294e92a4f6315fe24e0633b753b6d70fd
paleobot/pbot-client@190e30df467dfdc29cdedc8bdbe492ba6e6cd79a
paleobot/pbot-client@304c0cf13955d472481124ac042bedb675410daa

OTU search is on the merged description of the old Example Specimens.

Reconfiguration of Specimens in OTUs into Identified/Type/Holotype has not yet been implemented. When it is, OTU search will use the merged Type Specimens description.

**Comment by NoisyFlowers** [comment]
The change to Identified/Type/Holotype Specimens is in:

paleobot/pbot-api@502e282469e8aada52642fedf25747e39f8c4ca6
paleobot/pbot-client@65a57deb36c4c274ddd587d7af8ccd0b8506bad6
paleobot/pbot-client@5dff2ecec4ae9241cee5f4e68427796201f75106
