### ISSUE TITLE
Add idigbio lookup to Workbench -> Specimen form

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#92]
Documentation on the idigbio https://github.com/idigbio/idigbio-search-api/wiki is here. Approximately functionality should mirror implementation of the equivalent pbdb_id lookup forms.

**Comment by NoisyFlowers** [comment]
The problem I see here is that, cross-referening the Specimen input fields [(https://github.com/paleobot/pbot-dev/blob/main/Field%20definitions/Specimen%20fields%20v2.md)](https://github.com/paleobot/pbot-dev/blob/main/Field%20definitions/Specimen%20fields%20v2.md) with the idigbio query fields [(https://github.com/idigbio/idigbio-search-api/wiki/Index-Fields#record-query-fields)](https://github.com/idigbio/idigbio-search-api/wiki/Index-Fields#record-query-fields), I don't see many (any?) fields we can use to query the idigbio db.

**Comment by NoisyFlowers** [comment]
We decided to use institution code and catalog number. This is in 

paleobot/pbot-api@97d22072700a9e034be4c496ad95968f53d44217.

and 

paleobot/pbot-client@81547945e26dda5318413ac8b15da692197478ef
paleobot/pbot-client@9604c6d17a998ae14eae7b784b55bd6dbbdb4d0c
paleobot/pbot-client@36afd5edad4e98ddc18aca6f7d1ef73ba9f1231b
paleobot/pbot-client@2dbe1a6e7a3aadaa15ee88876b4112960323ecdb
