### ISSUE TITLE
The workflow for adding/editing characterInstances is too lengthy

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#96]
We need to develop a method for "breaking up" the process of adding new characterInstances to a description. This is vital when dealing with longer schemas.

**Comment by aazaff** [comment]
It would be nice if whatever solution for this we come up with could double-up and resolve #97

**Comment by NoisyFlowers** [comment]
CharacterInstance creation is now part of the Description forms of Workbench. 

The user must create the Description first. Then, in edit mode, CharacterInstances are added via a CharacterInstance accordion. Each CharacterInstance is added in a separate mutation. 

There was a lot of trial and error before we settled on an interface that we liked. This is reflected in the number of commits.

paleobot/pbot-client@13bf486df2688fec29b7441431e77b227dcaabba
paleobot/pbot-client@52e6bb9bafe2a33fd7393be9729f732a6054c8a3
paleobot/pbot-client@19abe3bcbe2442c210b25408802386db4329d984
paleobot/pbot-client@c00150b30dbc5b605bab5f5251571384ff3e9120
paleobot/pbot-client@54bd616450634ca61ae05cba2bb430928fea6e72
paleobot/pbot-client@c1b2d3d65934cf80c22786272fc173a38cd91083
paleobot/pbot-client@4242b74622061261e35f9fcc80c99181924671d0
paleobot/pbot-client@e8c26ff9aeebed8bbe867cb5bb18e3395430aa49
paleobot/pbot-client@99250721138d805cccbd87741e442bf404ae813f
paleobot/pbot-client@45784855ca3461e8ab89100555e1869377939498
paleobot/pbot-client@88a5edc0ac44c484704aac4c43d73f059d96e347
paleobot/pbot-client@f0a25eb72b77c2680a6b928e3277e0735a97c018
paleobot/pbot-client@fd474baa746c512f678017fb5aa47764d4879487
paleobot/pbot-client@50aad8a9d3af6522360178863a02a47c8332ecf3
paleobot/pbot-client@77007fd2a0ece9a12c30857d7e7ea2d8ef2c3d33
paleobot/pbot-client@eef999c6f0f0f5dd85c77878130b02757998ec7a
paleobot/pbot-client@6705410e881a332685edb4cf879df78b79fe6daf
paleobot/pbot-client@413be7bea1ffba2286c90dba253038426e4626b9
paleobot/pbot-client@63f6374d819ac67de555c212bc851d21ad5a7140
