### ISSUE TITLE
Cycle through all forms and replace any "long" dropdowns with search button workflow

### ISSUE THREAD

**Issue by aazaff** [paleobot/pbot-dev#98]

**Comment by aazaff** [comment]
@NoisyFlowers Just tagging you as proof I really did make an issue on this in April.

**Comment by aazaff** [comment]
See closed “duplicate” issues for specific instances

**Comment by doricon** [comment]
Add to description node, edit function.

**Comment by doricon** [comment]
Add to OTU entry form, identified specimens field.

**Comment by ecurrano** [comment]
Add to Description entry form, specimens

**Comment by ecurrano** [comment]
Add to Specimen entry form, collections field.

**Comment by ecurrano** [comment]
Add to Image entry form, collections field.

**Comment by ecurrano** [comment]
Add to Image entry form, specimen field

**Comment by ecurrano** [comment]
Add to Group entry form, members field

**Comment by NoisyFlowers** [comment]
SpecimenManager implemented for Description mutation form. This is in:
paleobot/pbot-client@d1a8ed2fe73ee4db689b7fef2c0b91454294f498
paleobot/pbot-client@581d6f9d463191565f0899b230f7eee367f8431e
paleobot/pbot-client@84ad6cd06d3967661d50a248cbe9e80574850750
paleobot/pbot-client@5c40e51c05c7a8d1aab0873f8125b9729191dd79

**Comment by NoisyFlowers** [comment]
SpecimenManager use expanded to OTU and Image mutation forms. This is in:
paleobot/pbot-client@4227e411be8d223d10b45de7e90fca871d504cc3
paleobot/pbot-client@9dc7dcae61774ad5437d262f86d9dd6f6c776232
paleobot/pbot-client@dc7478b3cf056b8ff2e9b918594c88133543672d
paleobot/pbot-client@5170c80e07bca2cbaa17cae43a0af0fb4976941e
paleobot/pbot-client@5bd044a0cfa54df7240a87b224071acd9655fb9d
paleobot/pbot-client@3f19b57d887a4e930ebbe8b21927e7009aeb963e
paleobot/pbot-client@c33046af44f5f54a409670f011d5fe9e0b955e5c
paleobot/pbot-client@bbd9af03fd35d718f3fa550a7e20b142a94dceb8
paleobot/pbot-client@83d3b0891c859adf46de95727a96f449dab288b4
paleobot/pbot-client@97f6edf9b5276b8fd637e7e7658762c99ca45860
paleobot/pbot-client@49a7ac35e9248741bf380cdbde631379db999e36
paleobot/pbot-client@cbe60df594197928bedc461c1f31a75cdf5e13bc

**Comment by NoisyFlowers** [comment]
Removed SpecimenSelect from Image mutation form.
paleobot/pbot-client@67d4edcdd9e4f7db4b47ec58ee5959ff5d5e1626

**Comment by NoisyFlowers** [comment]
Mag select implemented for Specimen and Collection edit mode. This is in:
paleobot/pbot-client@9e26c14b355f644675d7e7221aec2bbecc5a6849
paleobot/pbot-client@d5772909bf800b5d85a1fd15374154ae24b55a7d
paleobot/pbot-client@4cce9934186765cecdacc8b5ef9105bfb3a2d50f
paleobot/pbot-client@2eac57df3eb8a17e9fe3ba4b6cd6a82a6db51eeb
paleobot/pbot-client@203fe22d50273303ec7d0b8179da09e4f10f94dc
paleobot/pbot-client@68ae45ed500e1b3a600107af84dc8d0c632cb262
paleobot/pbot-client@7ca820303faa296c9753b18620c6d3aeb835f51a
paleobot/pbot-client@e9f665ed28eeb9811b1517e8cec230c7e88fd0f4
paleobot/pbot-client@e998f90a0c7b3e333ec7d15e8144b4c1016f81ab

**Comment by NoisyFlowers** [comment]
Description edit is in
paleobot/pbot-client@8d4aa5de4b1d35e2ea05e71c70656e717c425aca
paleobot/pbot-client@7beb471e6113801e16c8401c140dd5943b0fb09b
paleobot/pbot-client@ca473effa865275789571e1b36a00a0dcdc64c4a
paleobot/pbot-client@a2e4e239b0dcc29d7c3fbfe001b347dd57cc6e78
paleobot/pbot-client@ea5c81c047b3183be314c910a49d685c8b259286

This one was a pain, as we no longer support a Description query. The old one was still hanging around, and I was able to modify that.

**Comment by doricon** [comment]
I think this was all done, and if there are any others we should make a new specific issue. Closing it down!
